param([string]$StatePath="ENGREMIAT_MEMORY/operative/dashboard/dashboard-state.json",[string]$OutPath="ENGREMIAT_MEMORY/dashboard/memory/index.html",[switch]$Open)
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function ED($p){if($p -and !(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null}}
function E($s){return [System.Net.WebUtility]::HtmlEncode([string]$s)}
if(!(Test-Path -LiteralPath $StatePath -PathType Leaf)){throw "dashboard state missing: $StatePath"}
$st=Get-Content -LiteralPath $StatePath -Raw -Encoding UTF8|ConvertFrom-Json
$cards=@();$cards+="<div class='card ok'><h2>Objetivo activo</h2><p><b>"+(E $st.active_objective)+"</b></p><p>Stage: "+(E $st.active_stage)+"</p></div>";$cards+="<div class='card'><h2>Readiness</h2><p class='big'>"+(E $st.readiness)+"</p><p>Eventos: "+$st.events_count+" · Gates: "+$st.gates_count+" · Artefactos: "+$st.artifacts_count+"</p></div>";$cards+="<div class='card next'><h2>Siguiente</h2><p>"+(E $st.next)+"</p></div>"
$okHtml="<ul>";foreach($e in @($st.last_ok)){$okHtml+="<li>OK · "+(E $e.stage_id)+" · "+(E $e.source_path)+"</li>"};$okHtml+="</ul>";$issueHtml="<ul>";foreach($e in @($st.last_issue)){$issueHtml+="<li>"+(E $e.status)+" · "+(E $e.stage_id)+" · "+(E $e.source_path)+"</li>"};$issueHtml+="</ul>";$mapHtml="<ul>";foreach($m in @($st.maps)){$mapHtml+="<li><code>"+(E $m)+"</code></li>"};$mapHtml+="</ul>"
$html=@("<!doctype html><html lang='es'><head><meta charset='utf-8'><title>ENGREMIAT Visual Memory Operative</title><style>body{font-family:Arial;margin:0;background:#f3f5f7;color:#17202a}.top{background:#101828;color:white;padding:22px 30px}.wrap{padding:22px 30px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.card{background:white;border:1px solid #d0d5dd;border-radius:12px;padding:16px;box-shadow:0 1px 2px #ddd}.ok{border-left:6px solid #16a34a}.next{border-left:6px solid #7c3aed}.warn{border-left:6px solid #f59e0b}.bad{border-left:6px solid #dc2626}.big{font-size:32px;font-weight:bold}code{background:#eef2f7;padding:2px 5px;border-radius:4px}li{margin:5px 0}</style></head><body>","<div class='top'><h1>ENGREMIAT Visual Memory Operative</h1><p>updated_at: "+(E $st.updated_at)+" · external_network=False</p></div>","<div class='wrap'><div class='grid'>"+($cards -join "")+"</div>","<div class='grid'><div class='card ok'><h2>Últimos OK</h2>"+$okHtml+"</div><div class='card bad'><h2>Últimos ERR / NO_GO</h2>"+$issueHtml+"</div></div>","<div class='card'><h2>Mapas y navegación</h2>"+$mapHtml+"</div>","<div class='card warn'><h2>Comandos esperados</h2><p><code>.\eng.ps1 memory-sync</code> · <code>.\eng.ps1 memory-dashboard</code></p></div></div></body></html>")
ED (Split-Path -Parent $OutPath);Set-Content -LiteralPath $OutPath -Value $html -Encoding UTF8;if($Open){try{Start-Process (Resolve-Path $OutPath)}catch{}};Write-Host ("OK dashboard_html=True output="+$OutPath)
