param([string]$Command="memory-status",[switch]$NoOpen)
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function Run($p,$a=@()){ if(Test-Path -LiteralPath $p -PathType Leaf){ & powershell -NoProfile -ExecutionPolicy Bypass -File $p @a; if($LASTEXITCODE -ne 0){ throw "Command failed: $p" } } }
function ReadState(){ if(Test-Path -LiteralPath "ENGREMIAT_MEMORY/operative/dashboard/dashboard-state.json" -PathType Leaf){ return (Get-Content -LiteralPath "ENGREMIAT_MEMORY/operative/dashboard/dashboard-state.json" -Raw -Encoding UTF8 | ConvertFrom-Json) }; return $null }
if($Command -in @("memory-sync","sync")){ Run "tools/memory/Scan-EngremiatEvidence.ps1"; Run "tools/memory/Convert-EvidenceToDevelopmentEvent.ps1"; Run "tools/memory/Sync-VisualMemory.ps1"; Run "tools/memory/Update-LogseqHome.ps1"; Run "tools/memory/Update-VisualMaps.ps1"; Run "tools/memory/Build-VisualDashboardData.ps1"; Run "tools/memory/Build-VisualDashboardHtml.ps1"; Write-Host "OK memory_sync=True next=memory-dashboard"; exit 0 }
if($Command -in @("memory-dashboard","dashboard")){ Run "tools/memory/Build-VisualDashboardData.ps1"; if($NoOpen){ Run "tools/memory/Build-VisualDashboardHtml.ps1" } else { Run "tools/memory/Build-VisualDashboardHtml.ps1" @("-Open") }; Write-Host "OK memory_dashboard=True path=ENGREMIAT_MEMORY/dashboard/memory/index.html"; exit 0 }
if($Command -in @("memory-graph","graph")){ if(Test-Path -LiteralPath "tools/memory/Export-MemoryGraphJsonl.ps1" -PathType Leaf){ Run "tools/memory/Export-MemoryGraphJsonl.ps1" }; $n=0;$e=0;if(Test-Path -LiteralPath "ENGREMIAT_MEMORY/graph/export/nodes.jsonl"){$n=(Get-Content -LiteralPath "ENGREMIAT_MEMORY/graph/export/nodes.jsonl" -Encoding UTF8|Where-Object{![string]::IsNullOrWhiteSpace($_)}).Count};if(Test-Path -LiteralPath "ENGREMIAT_MEMORY/graph/export/edges.jsonl"){$e=(Get-Content -LiteralPath "ENGREMIAT_MEMORY/graph/export/edges.jsonl" -Encoding UTF8|Where-Object{![string]::IsNullOrWhiteSpace($_)}).Count}; Write-Host ("OK memory_graph=True nodes="+$n+" edges="+$e); exit 0 }
if($Command -in @("memory","memory-status","status")){ $st=ReadState; if($null -eq $st){ Run "tools/memory/Build-VisualDashboardData.ps1"; $st=ReadState }; if($null -eq $st){ throw "dashboard-state unavailable" }; Write-Host ("OK memory_status=True objective="+$st.active_objective+" stage="+$st.active_stage+" readiness="+$st.readiness+" events="+$st.events_count+" gates="+$st.gates_count+" artifacts="+$st.artifacts_count+" next="+$st.next); exit 0 }
Write-Host "Uso: .\eng.ps1 memory | memory-status | memory-sync | memory-dashboard | memory-graph"; exit 0
