param([string]$EventsPath="ENGREMIAT_MEMORY/operative/events/events.jsonl",[string]$MapsRoot="ENGREMIAT_MEMORY/maps")
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function ED($p){ if($p -and !(Test-Path -LiteralPath $p)){ New-Item -ItemType Directory -Path $p -Force | Out-Null } }
ED $MapsRoot; $events=@(); if(Test-Path -LiteralPath $EventsPath -PathType Leaf){ foreach($l in Get-Content -LiteralPath $EventsPath -Encoding UTF8){ if([string]::IsNullOrWhiteSpace($l)){continue}; try{$events+=($l|ConvertFrom-Json)}catch{} } }
$ok=@($events|Where-Object{$_.status -eq "OK"}); $bad=@($events|Where-Object{$_.status -eq "ERR" -or $_.status -eq "NO_GO"}); $ready=@($events|Where-Object{$_.status -eq "READY" -or $_.status -eq "CLOSE"}); $objectives=@($events|Group-Object objective_id); $lines=@("# OPERATIVE_OVERVIEW","","- generated_at: "+(Get-Date).ToString("s"),"- events_count: "+$events.Count,"- ok_count: "+$ok.Count,"- issue_count: "+$bad.Count,"- ready_or_close_count: "+$ready.Count,"","## Objectives"); foreach($g in $objectives){$lines+="- [["+$g.Name+"]] events="+$g.Count}; $lines+=""; $lines+="## Next"; $lines+="- E03_DASHBOARD_OPERATIVO"; Set-Content -LiteralPath (Join-Path $MapsRoot "OPERATIVE_OVERVIEW.md") -Value $lines -Encoding UTF8
$err=@("# ERRORS_MAP","","- generated_at: "+(Get-Date).ToString("s"),"- issue_count: "+$bad.Count,"","## Latest issues"); foreach($e in @($bad|Select-Object -Last 50)){$err+="- "+$e.status+" · "+$e.objective_id+" · "+$e.stage_id+" · "+$e.source_path}; Set-Content -LiteralPath (Join-Path $MapsRoot "ERRORS_MAP.md") -Value $err -Encoding UTF8
$dec=@("# DECISIONS_MAP","","## Active decisions","- Visual Memory Operative 002 continues after Visual Memory Ready.","- Dashboard operative is next after live navigation.","- Graphiti real remains blocked by future gate.","","## Evidence","- events_count: "+$events.Count); Set-Content -LiteralPath (Join-Path $MapsRoot "DECISIONS_MAP.md") -Value $dec -Encoding UTF8
$gates=@("# GATES_MAP","","- generated_at: "+(Get-Date).ToString("s"),"- gate_policy: HUMAN_GATE_BEFORE_APPLY","","## Gate sources"); if(Test-Path -LiteralPath "data/gates"){$gs=Get-ChildItem -LiteralPath "data/gates" -Recurse -File -ErrorAction SilentlyContinue; foreach($g in @($gs|Select-Object -First 80)){$gates+="- "+$g.FullName.Replace((Get-Location).Path+"\","").Replace("\","/")}}else{$gates+="- no data/gates folder detected"}; Set-Content -LiteralPath (Join-Path $MapsRoot "GATES_MAP.md") -Value $gates -Encoding UTF8
$workers=@("# WORKERS_MAP","","- Assisted Worker Adapter: proposal-only by default.","- Apply requires human gate.","- External workers are evidence sources, not decision makers.","","## Related","- [[GATES_MAP]]","- [[OPERATIVE_OVERVIEW]]"); Set-Content -LiteralPath (Join-Path $MapsRoot "WORKERS_MAP.md") -Value $workers -Encoding UTF8
Write-Host ("OK visual_maps=True events="+$events.Count+" maps="+$MapsRoot)
