$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$Root = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path))
$ReportDir = Join-Path $Root "reports\launcher-health"
function Invoke-HumanCardAssistant(){ $assistant = Join-Path $Root "tools\human-card-assistant.ps1"; if(Test-Path $assistant){ & powershell -NoProfile -ExecutionPolicy Bypass -File $assistant } else { W "PENDIENTE asistente tarjetas humanas" Yellow; Read-Host "Enter = volver" | Out-Null } }
function W([string]$Text,[string]$Color="Gray"){ Write-Host $Text -ForegroundColor $Color }
function Test-LauncherPath([string]$Label,[string]$Relative){ $path=Join-Path $Root $Relative; $exists=Test-Path $path; $status=if($exists){"OK"}else{"PENDING"}; $color=if($exists){"Green"}else{"Yellow"}; W ($status+" "+$Label+" -> "+$Relative) $color; return [ordered]@{label=$Label;relative=$Relative;path=$path;exists=$exists} }
function Run-Health(){ New-Item -ItemType Directory -Force -Path $ReportDir | Out-Null; Clear-Host; W "==== ENGREMIAT / HEALTH LAUNCHERS ====" Cyan; W ""; W ("Root: "+$Root) DarkGray; W "Contrato: revisar launchers reales enlazados desde ENGREMIAT.ps1" DarkGray; W ""; $items=@(); $items+=Test-LauncherPath "Launcher maestro" "ENGREMIAT.ps1"; $items+=Test-LauncherPath "Inicio operador" "tools\launcher\ENGREMIAT-LAUNCHER-ACTUAL.ps1"; $items+=Test-LauncherPath "Asistente tarjetas humanas" "tools\human-card-assistant.ps1"; $items+=Test-LauncherPath "Data Intake" "tools\data-intake.ps1"; $items+=Test-LauncherPath "Health launchers" "tools\health\health-launchers.ps1"; W ""; $ok=($items|Where-Object {$_.exists}).Count; $total=$items.Count; $missing=($items|Where-Object {-not $_.exists}).Count; $status=if($missing -eq 0){"PASS"}else{"WARN"}; W ("RESUMEN status="+$status+" ok="+$ok+" missing="+$missing+" total="+$total) $(if($missing -eq 0){"Green"}else{"Yellow"}); $report=Join-Path $ReportDir ("health-launchers-"+(Get-Date -Format "yyyyMMdd-HHmmss")+".json"); $payload=[ordered]@{package="ENGREMIAT_REAL_PROJECT_WALKTHROUGH_001";stage="E02J_CREATE_HEALTH_LAUNCHERS_MINIMAL_REAL";status=$status;created_at=(Get-Date -Format s);root=$Root;items=$items}; Set-Content -Path $report -Value ($payload|ConvertTo-Json -Depth 6) -Encoding UTF8; W ("OK report="+$report) Green; W "NEXT si falta algun launcher, crear pantalla minima real o enrutar al asistente de tarjetas." Cyan; W ""; W "[b/q] salir/volver | m = mantenimiento | ? = ayuda | Enter = refrescar" DarkGray; W ""; $cmd=Read-Host "HEALTH"; $cmd=($cmd+"").Trim().ToLowerInvariant(); if($cmd -eq "m"){ Invoke-HumanCardAssistant } elseif($cmd -eq "?"){ W ""; W "AYUDA" Cyan; W "Este health comprueba que las opciones del launcher maestro apunten a scripts reales." White; Read-Host "Enter = volver" | Out-Null } }
while($true){ Run-Health; $again=Read-Host "Enter = refrescar | b/q = volver"; $again=($again+"").Trim().ToLowerInvariant(); if($again -eq "b" -or $again -eq "q"){ break } }


