$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$CardRoot = Join-Path $Root "documents\human-cards"
$Inbox = Join-Path $CardRoot "_inbox"
$Index = Join-Path $CardRoot "_index"
$CommonCommandLegend = "[b/q] salir/volver | m = mantenimiento | ? = ayuda | Enter = refrescar"
function W([string]$Text,[string]$Color="Gray"){ Write-Host $Text -ForegroundColor $Color }
function Ensure-Dirs(){ foreach($d in @($CardRoot,$Inbox,$Index,(Join-Path $CardRoot "observer-review"),(Join-Path $CardRoot "tasks"),(Join-Path $CardRoot "archive"))){ New-Item -ItemType Directory -Force -Path $d | Out-Null } }
function SafeText([string]$v){ if([string]::IsNullOrWhiteSpace($v)){ return "SIN_TITULO" }; return (($v -replace "[^a-zA-Z0-9 _.-]","_").Trim()) }
function Is-Cancel([string]$v){ $x=($v+"").Trim().ToLowerInvariant(); return ($x -eq "b" -or $x -eq "q" -or $x -eq "cancel" -or $x -eq "cancelar" -or $x -eq "salir") }
function Read-FormValue([string]$Prompt,[string]$Default){ $v=Read-Host ($Prompt+" [b/q/cancel = cancelar]"); if(Is-Cancel $v){ return $null }; if([string]::IsNullOrWhiteSpace($v)){ return $Default }; return $v }
function Wait-Back(){ W ""; Read-Host "Enter = volver" | Out-Null }
function Show-Maintenance(){ Ensure-Dirs; W ""; W "MANTENIMIENTO" Cyan; W ("Almacen tarjetas: "+$CardRoot) White; W ("Inbox: "+$Inbox) White; W ("Indice observer: "+(Join-Path $Index "observer-inbox.jsonl")) White; W "Contrato: humano -> tarjeta/tarea -> indice observable -> observer" White; Wait-Back }
function Show-Help(){ W ""; W "AYUDA" Cyan; W "1 = crear tarjeta para revision del observer." White; W "2 = crear tarea humana general." White; W "3 = ver inbox de tarjetas." White; W "4 = ver indice observable del observer." White; W "m = mantenimiento de esta pantalla." White; W "b/q = salir o volver a la pantalla anterior." White; W "Enter vacio = refrescar pantalla." White; W "Durante la creacion de tarjeta: b/q/cancel = cancelar sin guardar." White; Wait-Back }
function New-HumanCard([string]$Kind){ Ensure-Dirs; W ""; W "CREAR TARJETA HUMANA" Cyan; W "Puedes escribir b, q, cancel, cancelar o salir en cualquier campo para cancelar sin guardar." DarkGray; $title=Read-FormValue "Titulo breve de la tarjeta" "Revision humana"; if($null -eq $title){ W "CANCELADO no se creo tarjeta." Yellow; Wait-Back; return }; $summary=Read-FormValue "Resumen / decision necesaria" "Pendiente de completar por humano"; if($null -eq $summary){ W "CANCELADO no se creo tarjeta." Yellow; Wait-Back; return }; $priority=Read-FormValue "Prioridad [LOW/MEDIUM/HIGH]" "MEDIUM"; if($null -eq $priority){ W "CANCELADO no se creo tarjeta." Yellow; Wait-Back; return }; $priority=($priority+"").Trim().ToUpperInvariant(); if($priority -notin @("LOW","MEDIUM","HIGH")){ $priority="MEDIUM" }; $now=Get-Date; $day=$now.ToString("yyyy\\MM\\dd"); $dir=Join-Path $Inbox $day; New-Item -ItemType Directory -Force -Path $dir | Out-Null; $id="HC-"+$now.ToString("yyyyMMdd-HHmmss")+"-"+(Get-Random -Minimum 1000 -Maximum 9999); $file=Join-Path $dir ($id+"-"+(SafeText $Kind)+".md"); $created=$now.ToString("s"); $body=@("# Tarjeta humana","","id: "+$id,"kind: "+$Kind,"status: PENDING_HUMAN_REVIEW","priority: "+$priority,"created_at: "+$created,"source: human-card-assistant","observer_access: documents/human-cards/_index/observer-inbox.jsonl","","## Titulo",$title,"","## Resumen / decision necesaria",$summary,"","## Checklist","- [ ] Revisar contexto","- [ ] Decidir siguiente accion","- [ ] Marcar decision","","## Decision","PENDING"); Set-Content -Path $file -Value $body -Encoding UTF8; $entry=[ordered]@{id=$id;kind=$Kind;status="PENDING_HUMAN_REVIEW";priority=$priority;created_at=$created;title=$title;summary=$summary;path=$file;observer_visible=$true}; $json=($entry|ConvertTo-Json -Compress); Add-Content -Path (Join-Path $Index "observer-inbox.jsonl") -Value $json -Encoding UTF8; Set-Content -Path (Join-Path $Index "latest-card.json") -Value $json -Encoding UTF8; W ""; W ("OK human_card_created="+$file) Green; W ("OK observer_index="+(Join-Path $Index "observer-inbox.jsonl")) Green; W "NEXT observer puede leer _index/observer-inbox.jsonl y abrir path." Cyan; Wait-Back }
function Show-Inbox(){ Ensure-Dirs; W ""; W "INBOX TARJETAS HUMANAS" Cyan; $cards=Get-ChildItem $Inbox -Recurse -Filter *.md -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 20; if(!$cards){ W "Sin tarjetas." Yellow } else { $i=1; foreach($c in $cards){ W ("["+$i+"] "+$c.FullName) White; $i++ } }; Wait-Back }
function Show-Index(){ Ensure-Dirs; $idx=Join-Path $Index "observer-inbox.jsonl"; W ""; W "INDICE OBSERVER" Cyan; if(Test-Path $idx){ Get-Content $idx -Tail 20 | ForEach-Object { W $_ White } } else { W "Sin indice observer todavia." Yellow }; Wait-Back }
while($true){ Clear-Host; W "==== ENGREMIAT / ASISTENTE DE TARJETAS HUMANAS ====" Cyan; W ""; W ("Almacen: "+$CardRoot) DarkGray; W "Contrato: humano -> tarjeta/tarea -> indice observable -> observer" DarkGray; W ""; W "[1] Crear tarjeta para revision del observer" White; W "[2] Crear tarea humana general" White; W "[3] Ver inbox de tarjetas" White; W "[4] Ver indice observable del observer" White; W ""; W $CommonCommandLegend DarkGray; W ""; $cmd=Read-Host "TARJETAS"; $cmd=($cmd+"").Trim().ToLowerInvariant(); switch($cmd){ "" { continue } "1" { New-HumanCard "OBSERVER_REVIEW" } "2" { New-HumanCard "HUMAN_TASK" } "3" { Show-Inbox } "4" { Show-Index } "m" { Show-Maintenance } "?" { Show-Help } "h" { Show-Help } "help" { Show-Help } "b" { return } "q" { return } default { W "Comando no reconocido: $cmd" Yellow; Wait-Back } } }
