$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$Core="C:\ENGREMIAT_CORE"
$DataIntake=Join-Path $Core "tools\launcher\ENGREMIAT-DATA-INTAKE-CENTER-NORMALIZED.ps1"
function UX([string]$m,[string]$role="info"){$c=switch($role){"title"{"Cyan"}"route"{"DarkGray"}"role"{"Gray"}"principle"{"DarkGray"}"section"{"Yellow"}"ok"{"Green"}"warn"{"Yellow"}"err"{"Red"}"next"{"Cyan"}"muted"{"DarkGray"}default{"Gray"}};try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function W([string]$m,[string]$c="Gray"){try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function UXOk([string]$m){UX ("[OK] "+$m) "ok"}
function UXWarn([string]$m){UX ("[WARN] "+$m) "warn"}
function P(){Write-Host "";Read-Host "[Enter] volver / refrescar"|Out-Null}
function Header([string]$section=""){Clear-Host;UX "==== MEMORIA Y DOCUMENTACION / CENTRO DOCUMENTAL ====" "title";UX "Ruta: INICIO > Memoria y documentacion" "route";UX "Rol: consumidor documental de fichas, memoria viva y salidas humanas" "role";UX "Principio: Data Intake produce fichas; Centro Documental genera documentos" "principle";if($section){UX $section "section"};Write-Host ""}
function EnsureDir([string]$p){New-Item -ItemType Directory -Force -Path $p|Out-Null}
function EnsureDoc([string]$path,[string]$title,[string[]]$body){EnsureDir (Split-Path $path -Parent);if(!(Test-Path $path)){@("# $title","","Generado por Centro Documental normalizado.","Fecha: $(Get-Date -Format s)","") + $body | Set-Content $path -Encoding UTF8};return $path}
function OpenMd([string]$path,[string]$title,[string[]]$body){$p=EnsureDoc $path $title $body;Start-Process notepad.exe $p;Header $title;UXOk ("abierto: "+$p);P}
function ActiveProfilePath(){EnsureDir (Join-Path $Core "documents\grants");return (Join-Path $Core "documents\grants\grant-call-profile-latest.json")}
function EnsureProfile(){$p=ActiveProfilePath;if(!(Test-Path $p)){$o=[ordered]@{nombre_convocatoria="Convocatoria demo de innovacion social y economia circular";entidad_convocante="Entidad publica demo";territorio="Catalunya / España";fecha_limite="2026-12-31";objetivo_convocatoria="Financiar proyectos piloto con impacto social, economia circular y digitalizacion local.";lineas_prioritarias=@("Economia circular","Innovacion social","Digitalizacion local");importe_solicitado="50000 EUR";cofinanciacion="No requerida / pendiente de bases especificas";beneficiarios="Comunidades locales, entidades sociales y administraciones colaboradoras.";indicadores_requeridos=@("Personas beneficiarias","Tareas completadas","Evidencias documentadas");documentacion_requerida=@("Memoria tecnica","Presupuesto","Cronograma","Indicadores");criterios_valoracion=@("Innovacion social","Impacto medible","Viabilidad tecnica");tono="tecnico, claro, institucional y orientado a impacto";status="ready";human_review_required=$false;pending_fields=@()};$o|ConvertTo-Json -Depth 60|Set-Content $p -Encoding UTF8};return $p}
function Val($o,[string[]]$names,[string]$fallback="No definido"){foreach($n in $names){if($o.PSObject.Properties.Name -contains $n){$v=$o.$n;if($null -ne $v){$s=if($v -is [array]){($v -join ", ")}else{[string]$v};$s=$s.Trim();if($s -and $s -ne "No definido" -and $s -ne "PENDIENTE_DEFINIR"){return $s}}}};return $fallback}
function Arr($o,[string[]]$names,[string[]]$fallback){foreach($n in $names){if($o.PSObject.Properties.Name -contains $n -and $null -ne $o.$n){$a=@($o.$n)|Where-Object{$_ -and ([string]$_).Trim() -and $_ -ne "No definido" -and $_ -ne "PENDIENTE_DEFINIR"};if($a.Count){return $a}}};return $fallback}
function EditGrantProfile(){$p=EnsureProfile;Start-Process notepad.exe $p;Header "FICHA DE CONVOCATORIA";UXOk ("ficha abierta: "+$p);P}
function GenerateAdaptedDossier(){$p=EnsureProfile;$j=Get-Content $p -Raw|ConvertFrom-Json;$dir=Join-Path $Core "documents\grants";$stamp=Get-Date -Format "yyyyMMdd-HHmmss";$latest=Join-Path $dir "dossier-subvenciones-adaptado-latest.md";$version=Join-Path $dir ("dossier-subvenciones-adaptado-"+$stamp+".md");$reportDir=Join-Path $Core "reports\launcher";EnsureDir $dir;EnsureDir $reportDir;$nombre=Val $j @("nombre_convocatoria","convocatoria_nombre","titulo");$entidad=Val $j @("entidad_convocante","entity");$territorio=Val $j @("territorio","territory");$fecha=Val $j @("fecha_limite","deadline");$objetivo=Val $j @("objetivo_convocatoria","summary","resumen");$importe=Val $j @("importe_solicitado","importe_maximo","amount");$cofin=Val $j @("cofinanciacion");$benef=Val $j @("beneficiarios");$tono=Val $j @("tono") "tecnico, claro, institucional y orientado a impacto";$lineas=Arr $j @("lineas_prioritarias") @("Economia circular","Innovacion social");$indicadores=Arr $j @("indicadores_requeridos") @("Personas beneficiarias","Evidencias documentadas");$docs=Arr $j @("documentacion_requerida","required_documents") @("Memoria tecnica","Presupuesto");$criterios=Arr $j @("criterios_valoracion","criterios","criteria") @("Impacto medible","Viabilidad tecnica");$out=@("# Dossier adaptado a convocatoria","","## Convocatoria",$nombre,"","## Entidad convocante",$entidad,"","## Territorio",$territorio,"","## Fecha limite",$fecha,"","## Objetivo de la convocatoria",$objetivo,"","## Lineas prioritarias")+($lineas|ForEach-Object{"- "+$_})+@("","## Importe solicitado",$importe,"","## Cofinanciacion",$cofin,"","## Beneficiarios",$benef,"","## Indicadores requeridos")+($indicadores|ForEach-Object{"- "+$_})+@("","## Documentacion requerida")+($docs|ForEach-Object{"- "+$_})+@("","## Criterios de valoracion")+($criterios|ForEach-Object{"- "+$_})+@("","## Tono",$tono,"","## Encaje Engremiat","Engremiat se presenta como infraestructura local-first para convertir entradas de datos en fichas, documentos, tareas, modulos y evidencias con supervision humana.");$out|Set-Content $latest -Encoding UTF8;Copy-Item $latest $version -Force;$rep=Join-Path $reportDir ("grant-adapted-dossier-normalized-"+$stamp+".json");[pscustomobject]@{status="PASS";dossier=$latest;version=$version;source_profile=$p}|ConvertTo-Json -Depth 50|Set-Content $rep -Encoding UTF8;Header "DOSSIER ADAPTADO GENERADO";UXOk ("dossier: "+$latest);UXOk ("version: "+$version);UXOk ("report: "+$rep);P}
function AssistGrantProfile(){Header "ASISTENTE FICHA";UXWarn "Asistente minimo: abre la ficha JSON para edicion segura.";EditGrantProfile}
function OpenDataIntake(){if(Test-Path $DataIntake){& powershell -NoProfile -ExecutionPolicy Bypass -File $DataIntake}else{Header "DATA INTAKE NO ENCONTRADO";UXWarn $DataIntake;P}}
function DossierSubvenciones(){OpenMd (Join-Path $Core "documents\dossier-subvenciones-latest.md") "DOSSIER SUBVENCIONES" @("## Proposito","Base documental para subvenciones.","","## Estado","Pendiente de ampliar desde fichas y evidencias.")}
function DossierPartners(){OpenMd (Join-Path $Core "documents\dossier-partners-latest.md") "DOSSIER PARTNERS" @("## Proposito","Explicar Engremiat a posibles entidades colaboradoras.","","## Estado","Pendiente de ampliar con propuesta de valor y casos.")}
function DossierClientes(){OpenMd (Join-Path $Core "documents\dossier-clientes-latest.md") "DOSSIER CLIENTES" @("## Proposito","Explicar Engremiat a clientes o usuarios potenciales.","","## Estado","Pendiente de ampliar con beneficios y ejemplos.")}
Write-Host "[b/q] salir/volver  |  m = asistente tarjetas humanas  |  ? = ayuda  |  Enter = refrescar" -ForegroundColor DarkGray
function SubConvocatorias(){while($true){Header "CONVOCATORIAS Y FICHAS";UX "[1] crear/editar ficha de convocatoria";UX "[2] generar dossier adaptado a convocatoria";UX "[3] asistente rellenar ficha convocatoria";UX "[4] Data Intake / Entrada de datos y fichas";Write-Host "";UX "[b] volver | [Enter] refrescar | ? = ayuda" "muted";Write-Host "";$op=Read-Host "CONVOCATORIAS";switch($op){"1"{EditGrantProfile};"2"{GenerateAdaptedDossier};"3"{AssistGrantProfile};"4"{OpenDataIntake};"b"{return};""{continue};"?"{Header "AYUDA CONVOCATORIAS";UX "[1] ficha. [2] dossier. [3] asistente. [4] Data Intake normalizado.";P};default{UXWarn "Opcion no reconocida";Start-Sleep -Milliseconds 700}}}}
function PlaceholderSub([string]$title,[string[]]$items){while($true){Header $title;foreach($i in $items){UX $i};Write-Host "";UX "[b] volver | [Enter] refrescar | ? = ayuda" "muted";Write-Host "";$op=Read-Host "DOCUMENTACION_SUBMENU";switch($op){"b"{return};""{continue};"?"{Header ("AYUDA "+$title);UX "Pantalla propia creada. Handlers reales pendientes de cablear en fase posterior.";P};default{UXWarn "Handler pendiente de cablear en siguiente fase";Start-Sleep -Milliseconds 700}}}}
function StatusHelp(){Header "ESTADO Y AYUDA";UXOk "Modelo canonico aplicado";UXOk "Paleta UX integrada";UXOk "Centro Documental conectado a Data Intake normalizado";UXWarn "Pendiente: memoria viva, contexto worker, exportaciones y carpetas";P}
function Menu(){while($true){Header;UX "[1] Memoria viva";UX "[2] Dossiers";UX "[3] Convocatorias y fichas";UX "[4] Contexto worker / continuidad";UX "[5] Exportaciones y herramientas";UX "[6] Carpetas y archivos";UX "[7] Estado y ayuda";Write-Host "";UX "[b] volver | [Enter] refrescar | ? = ayuda" "muted";Write-Host "";$op=Read-Host "DOCUMENTACION";switch($op){"1"{PlaceholderSub "MEMORIA VIVA" @("[1] abrir memoria tecnica","[2] abrir resumen humano","[3] abrir informe de desarrollo")};"2"{SubDossiers};"3"{SubConvocatorias};"4"{PlaceholderSub "CONTEXTO WORKER / CONTINUIDAD" @("[1] abrir contexto worker","[2] abrir contexto JSON")};"5"{PlaceholderSub "EXPORTACIONES Y HERRAMIENTAS" @("[1] exportar documentos DOCX/HTML con Pandoc","[2] abrir carpeta exports","[3] verificar herramientas documentales")};"6"{PlaceholderSub "CARPETAS Y ARCHIVOS" @("[1] abrir carpeta documents")};"7"{StatusHelp};"b"{return};""{continue};"?"{Header "AYUDA";UX "Pantalla canonica. Numeros locales por pantalla. Enter refresca, b vuelve, ? ayuda.";P};default{UXWarn "Opcion no reconocida";Start-Sleep -Milliseconds 700}}}}
Menu

