param([string]$CardPath="",[string]$CardId="")
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$Core="C:\ENGREMIAT_CORE"
$ProposalDir=Join-Path $Core "documents\module-cards\proposals"
$BlueprintDir=Join-Path $Core "documents\module-cards\blueprints"
$GateDir=Join-Path $Core "documents\module-cards\gates"
$DecisionDir=Join-Path $Core "documents\module-cards\gate-decisions"
$DecisionValidator=Join-Path $Core "tools\module-cards\validate-human-gate-decision.ps1"
function W($m,$c="Gray"){try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function Short($s,$n=120){$v=[string]$s;if($v.Length -le $n){return $v};return $v.Substring(0,$n)}
function FindCardPath($id){$tablePath=Join-Path $Core "documents\module-cards\project-module-card-table.normalized.json";if(Test-Path $tablePath){$t=Get-Content $tablePath -Raw|ConvertFrom-Json;foreach($r in @($t.rows)){if([string]$r.card_id -eq $id -and $r.path){return [string]$r.path}}};$candidate=Join-Path (Join-Path $Core "documents\module-cards") ($id+".json");if(Test-Path $candidate){return $candidate};return ""}
function LatestProposal($id){if(!(Test-Path $ProposalDir)){return $null};return Get-ChildItem $ProposalDir -Filter ("CAP-"+$id+"-*.json") -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 1}
function LatestBlueprint($id){if(!(Test-Path $BlueprintDir)){return $null};return Get-ChildItem $BlueprintDir -Filter ("CAB-CAP-"+$id+"-*.json") -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 1}
function LatestGate($id){$bp=LatestBlueprint $id;if($null -eq $bp){return $null};$b=Get-Content $bp.FullName -Raw|ConvertFrom-Json;$gateId="HUMAN-GATE-"+[string]$b.blueprint_id;$candidate=Join-Path $GateDir ($gateId+".json");if(Test-Path $candidate){return Get-Item $candidate};return Get-ChildItem $GateDir -Filter ("HUMAN-GATE-*"+$id+"*.json") -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 1}
function LatestDecision($id){if(!(Test-Path $DecisionDir)){return $null};return Get-ChildItem $DecisionDir -Filter ("HGD-HUMAN-GATE-*"+$id+"*.json") -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 1}
function PauseBack(){Read-Host "Enter para volver"|Out-Null}
function ShowProposal($id){Clear-Host;W "==== TARJETA / PROPUESTA ====" Cyan;W "Modo: readonly | no ejecuta" DarkGray;W "";$f=LatestProposal $id;if($null -eq $f){W "No hay propuesta para esta tarjeta." Yellow}else{$p=Get-Content $f.FullName -Raw|ConvertFrom-Json;W ("PROPUESTA: "+$p.proposal_id) Green;W ("CARD:      "+$p.card_id);W ("ACCION:    "+$p.action);W ("ESTADO:    "+$p.status);W ("RIESGO:    "+$p.risk);W ("GATE:      "+$p.human_gate);W "";W "RAZON:" Cyan;W (Short $p.reason 500);W "";W "EXPECTED:" Cyan;W (Short $p.expected_output 500);W "";W "GUARDAS:" Cyan;foreach($g in @($p.forbidden_execution)){W (" - "+$g)};W "";W ("Archivo: "+$f.FullName) DarkGray};W "";PauseBack}
function ShowBlueprint($id){Clear-Host;W "==== TARJETA / BLUEPRINT ====" Cyan;W "Modo: readonly | NOT_EXECUTED" DarkGray;W "";$f=LatestBlueprint $id;if($null -eq $f){W "No hay blueprint para esta tarjeta." Yellow}else{$b=Get-Content $f.FullName -Raw|ConvertFrom-Json;W ("BLUEPRINT: "+$b.blueprint_id) Green;W ("PROPUESTA: "+$b.proposal_id);W ("CARD:      "+$b.card_id);W ("TIPO:      "+$b.blueprint_type);W ("ESTADO:    "+$b.status);W ("EXEC:      "+$b.execution_status);W ("DECISION:  "+$b.decision);W "";W "OBJETIVO:" Cyan;W (Short $b.objective 500);W "";W "PASOS PLANIFICADOS:" Cyan;foreach($s in @($b.planned_steps)){W (" - "+$s.step+" "+$s.name+" | "+$s.operation+" | executes="+$s.executes)};W "";W ("Archivo: "+$f.FullName) DarkGray};W "";PauseBack}
function ShowGate($id){Clear-Host;W "==== TARJETA / GATE HUMANO ====" Cyan;W "Modo: readonly | decision humana pendiente" DarkGray;W "";$f=LatestGate $id;if($null -eq $f){W "No hay gate humano para esta tarjeta." Yellow}else{$g=Get-Content $f.FullName -Raw|ConvertFrom-Json;W ("GATE:      "+$g.gate_id) Green;W ("CARD:      "+$g.card_id);W ("PROPUESTA: "+$g.proposal_id);W ("BLUEPRINT: "+$g.blueprint_id);W ("DECISION:  "+$g.decision);W ("ESTADO:    "+$g.status);W ("HUMAN:     "+$g.human_gate);W "";W "RAZON:" Cyan;W (Short $g.reason 500);W "";W "DECISIONES PERMITIDAS:" Cyan;foreach($d in @($g.allowed_decisions)){W (" - "+$d)};W "";W "GUARDAS:" Cyan;foreach($x in @($g.forbidden_execution)){W (" - "+$x)};W "";W ("Archivo: "+$f.FullName) DarkGray};W "";PauseBack}
function ShowDecision($id){Clear-Host;W "==== TARJETA / DECISION DRY-RUN ====" Cyan;W "Modo: readonly | no muta gate | no ejecuta" DarkGray;W "";$f=LatestDecision $id;if($null -eq $f){W "No hay decision dry-run para esta tarjeta." Yellow}else{if(Test-Path $DecisionValidator){& powershell -NoProfile -ExecutionPolicy Bypass -File $DecisionValidator -DecisionPath $f.FullName;W ""};$d=Get-Content $f.FullName -Raw|ConvertFrom-Json;W ("DECISION_ID: "+$d.decision_id) Green;W ("GATE:        "+$d.gate_id);W ("CARD:        "+$d.card_id);W ("PROPUESTA:   "+$d.proposal_id);W ("BLUEPRINT:   "+$d.blueprint_id);W ("DECISION:    "+$d.decision);W ("ESTADO:      "+$d.status);W ("MODO:        "+$d.mode);W ("HUMAN:       "+$d.human_gate);W "";W "RAZON:" Cyan;W (Short $d.reason 500);W "";W "EFECTOS PLANIFICADOS:" Cyan;foreach($e in @($d.effects_planned)){W (" - "+$e)};W "";W "EFECTOS APLICADOS:" Cyan;if(@($d.effects_applied).Count -eq 0){W " - ninguno"}else{foreach($e in @($d.effects_applied)){W (" - "+$e)}};W "";W "GUARDAS:" Cyan;foreach($x in @($d.forbidden_execution)){W (" - "+$x)};W "";W ("Archivo: "+$f.FullName) DarkGray};W "";PauseBack}
if([string]::IsNullOrWhiteSpace($CardPath) -and -not [string]::IsNullOrWhiteSpace($CardId)){$CardPath=FindCardPath $CardId}
Write-Host "[b/q] salir/volver | m = mantenimiento | ? = ayuda | Enter = refrescar" -ForegroundColor DarkGray
