$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$ModuleVault=if($args.Count -gt 0){[string]$args[0]}else{""}
$ModuleId=if($args.Count -gt 1){[string]$args[1]}else{"MODULE_inicio"}
$ProjectId=if($args.Count -gt 2){[string]$args[2]}else{"PROJECT_UNKNOWN"}
$ProjectTitle=if($args.Count -gt 3){[string]$args[3]}else{"Proyecto ENGREMIAT"}
$MasterVault=if($args.Count -gt 4){[string]$args[4]}else{""}
function L($m,$c="Gray"){Write-Host $m -ForegroundColor $c}
function D($p){if(!(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Force -Path $p|Out-Null}}
function W($p,[string[]]$a){$d=Split-Path $p -Parent;D $d;$a|Set-Content -LiteralPath $p -Encoding UTF8}
function J($p,$o){$d=Split-Path $p -Parent;D $d;$o|ConvertTo-Json -Depth 100|Set-Content -LiteralPath $p -Encoding UTF8}
if([string]::IsNullOrWhiteSpace($ModuleVault)){throw "module_vault_arg_empty"}
D $ModuleVault
foreach($p in @(".obsidian","00_CONTROL","00_CONTROL\OPERATIVE_CONTROL","00_CONTROL\GATES","00_CONTROL\RUNS","00_CONTROL\DECISIONS","00_CONTROL\RISKS","00_CONTROL\INTERFACES","01_CONTRATO","02_ROADMAP","03_TAREAS","04_EVIDENCIAS","05_RESULTADOS","06_APRENDIZAJE","07_CANVAS","08_PLANTILLAS","09_ARCHIVO","10_INDICE","11_SUPERFICIES_TRABAJO")){D (Join-Path $ModuleVault $p)}
J (Join-Path $ModuleVault ".obsidian\app.json") ([ordered]@{attachmentFolderPath="04_EVIDENCIAS";alwaysUpdateLinks=$true;newFileLocation="folder";newFileFolderPath="10_INDICE"})
J (Join-Path $ModuleVault ".obsidian\core-plugins.json") ([ordered]@{"file-explorer"=$true;"global-search"=$true;switcher=$true;graph=$true;backlink=$true;canvas=$true;"outgoing-link"=$true;"tag-pane"=$true;"page-preview"=$true;"command-palette"=$true;"note-composer"=$true;"file-recovery"=$true})
J (Join-Path $ModuleVault ".obsidian\graph.json") ([ordered]@{search="";showTags=$false;showAttachments=$false;hideUnresolved=$true;showOrphans=$true})
$masterLink=if($MasterVault -and (Test-Path -LiteralPath $MasterVault)){"[Abrir boveda maestra](obsidian://open?path=$([uri]::EscapeDataString($MasterVault)))"}else{"Boveda maestra no enlazada"}
W (Join-Path $ModuleVault "HOME.md") @("# $ModuleId","","## Tipo","Boveda operativa de modulo ENGREMIAT.","","## Proyecto",$ProjectTitle,"","## Funcion","Aqui se trabaja el detalle del modulo con control operativo, gates, riesgos, decisiones, evidencias, resultados y aprendizaje.","","## Volver a vision global",$masterLink,"","## Navegacion","- [[10_INDICE/INDICE_MODULO]]","- [[00_CONTROL/OPERATIVE_CONTROL/CONTROL_OPERATIVO]]","- [[01_CONTRATO/MODULE_CONTRACT]]","- [[02_ROADMAP/MODULE_ROADMAP]]","- [[03_TAREAS/TASK_INDEX]]","- [[04_EVIDENCIAS/EVIDENCE_INDEX]]","- [[05_RESULTADOS/RESULT_INDEX]]","- [[06_APRENDIZAJE/LEARNING_INDEX]]","- [[11_SUPERFICIES_TRABAJO/WORK_SURFACE_INDEX]]")
W (Join-Path $ModuleVault "10_INDICE\INDICE_MODULO.md") @("# Indice del modulo","","## Entrada","- [[../HOME]]","","## Control operativo","- [[../00_CONTROL/OPERATIVE_CONTROL/CONTROL_OPERATIVO]]","- [[../00_CONTROL/GATES/GATE_INDEX]]","- [[../00_CONTROL/DECISIONS/DECISION_INDEX]]","- [[../00_CONTROL/RISKS/RISK_INDEX]]","- [[../00_CONTROL/RUNS/RUN_INDEX]]","- [[../00_CONTROL/INTERFACES/INTERFACE_INDEX]]","","## Construccion","- [[../01_CONTRATO/MODULE_CONTRACT]]","- [[../02_ROADMAP/MODULE_ROADMAP]]","- [[../03_TAREAS/TASK_INDEX]]","","## Validacion","- [[../04_EVIDENCIAS/EVIDENCE_INDEX]]","- [[../05_RESULTADOS/RESULT_INDEX]]","- [[../06_APRENDIZAJE/LEARNING_INDEX]]","","## Uso","- [[../08_PLANTILLAS/TEMPLATE_INDEX]]","- [[../11_SUPERFICIES_TRABAJO/WORK_SURFACE_INDEX]]","- [[../09_ARCHIVO/ARCHIVE_INDEX]]")
W (Join-Path $ModuleVault "00_CONTROL\OPERATIVE_CONTROL\CONTROL_OPERATIVO.md") @("# Control operativo del modulo","","## Estado","draft","","## Principio","Nada pasa a ejecucion real sin gate humano.","","## Flujo","1. Contrato del modulo.","2. Roadmap del modulo.","3. Tareas.","4. Evidencias esperadas.","5. Smoke worker futuro.","6. Validacion humana.","7. Resultado y aprendizaje.","","## Indices","- [[../GATES/GATE_INDEX]]","- [[../RUNS/RUN_INDEX]]","- [[../DECISIONS/DECISION_INDEX]]","- [[../RISKS/RISK_INDEX]]")
W (Join-Path $ModuleVault "00_CONTROL\GATES\GATE_INDEX.md") @("# Gates del modulo","","- GATE_CONTRACT_APPROVAL pendiente.","- GATE_SMOKE_WORKER pendiente.","- GATE_RESULT_VALIDATION pendiente.")
W (Join-Path $ModuleVault "00_CONTROL\RUNS\RUN_INDEX.md") @("# Runs del modulo","","Aqui se registraran ejecuciones simuladas o smoke workers.")
W (Join-Path $ModuleVault "00_CONTROL\DECISIONS\DECISION_INDEX.md") @("# Decisiones del modulo","","Aqui se registraran decisiones humanas y tecnicas.")
W (Join-Path $ModuleVault "00_CONTROL\RISKS\RISK_INDEX.md") @("# Riesgos del modulo","","- Riesgo: ejecutar sin contrato claro.","- Riesgo: mezclar vision global con detalle modular.","- Riesgo: worker real sin evidencia esperada.")
Write-Host "[b/q] salir/volver | m = mantenimiento | ? = ayuda | Enter = refrescar" -ForegroundColor DarkGray
W (Join-Path $ModuleVault "01_CONTRATO\MODULE_CONTRACT.md") @("# Contrato $ModuleId","","## Proposito","Definir que construye el modulo, que entradas acepta y que evidencias debe producir.","","## Entradas","- Objetivo del proyecto.","- Limites.","- Criterio de aceptacion.","- Dependencias.","","## Salidas","- Tareas.","- Evidencias.","- Resultado.","- Aprendizaje.","","## Limites","Sin worker real hasta gate humano.")
W (Join-Path $ModuleVault "02_ROADMAP\MODULE_ROADMAP.md") @("# Roadmap $ModuleId","","1. Definir contrato.","2. Crear tareas.","3. Preparar evidencia esperada.","4. Ejecutar smoke worker futuro.","5. Validar resultado humano.")
W (Join-Path $ModuleVault "03_TAREAS\TASK_INDEX.md") @("# Tareas del modulo","","- T01 Definir contrato.","- T02 Preparar estructura.","- T03 Preparar smoke futuro.")
W (Join-Path $ModuleVault "04_EVIDENCIAS\EVIDENCE_INDEX.md") @("# Evidencias del modulo","","Aqui se guardaran evidencias generadas por simulacion o smoke worker.")
W (Join-Path $ModuleVault "05_RESULTADOS\RESULT_INDEX.md") @("# Resultados del modulo","","Aqui se registraran resultados validados.")
W (Join-Path $ModuleVault "06_APRENDIZAJE\LEARNING_INDEX.md") @("# Aprendizaje del modulo","","Aqui se registrara lo aprendido para reutilizarlo.")
W (Join-Path $ModuleVault "08_PLANTILLAS\TEMPLATE_INDEX.md") @("# Plantillas del modulo","","- Plantilla de contrato.","- Plantilla de tarea.","- Plantilla de evidencia.","- Plantilla de resultado.")
W (Join-Path $ModuleVault "09_ARCHIVO\ARCHIVE_INDEX.md") @("# Archivo del modulo","","Aqui se guardara material no activo.")
W (Join-Path $ModuleVault "11_SUPERFICIES_TRABAJO\WORK_SURFACE_INDEX.md") @("# Superficies de trabajo","","## Terminal","Trabajo operativo actual.","","## Obsidian","Vision y relacion de objetos.","","## Futuro","Dashboard / Telegram / OpenClaw.")
J (Join-Path $ModuleVault "00_CONTROL\module.json") ([ordered]@{module_id=$ModuleId;project_id=$ProjectId;type="operative_module_vault";status="draft";master_vault=$MasterVault;module_vault=$ModuleVault;purpose="Boveda independiente con control operativo de modulo";capabilities=@("contract","roadmap","tasks","gates","runs","decisions","risks","evidence","results","learning","work_surfaces","templates");next="definir-contrato-modulo";safety=[ordered]@{local_only=$true;no_worker_real=$true;no_git=$true;no_network=$true}})
$canvas=@{nodes=@(@{id="home";type="file";file="HOME.md";x=0;y=0;width=360;height=220},@{id="control";type="file";file="00_CONTROL/OPERATIVE_CONTROL/CONTROL_OPERATIVO.md";x=420;y=0;width=360;height=220},@{id="contract";type="file";file="01_CONTRATO/MODULE_CONTRACT.md";x=840;y=0;width=360;height=220},@{id="tasks";type="file";file="03_TAREAS/TASK_INDEX.md";x=1260;y=0;width=360;height=220},@{id="evidence";type="file";file="04_EVIDENCIAS/EVIDENCE_INDEX.md";x=840;y=280;width=360;height=220},@{id="result";type="file";file="05_RESULTADOS/RESULT_INDEX.md";x=1260;y=280;width=360;height=220},@{id="learning";type="file";file="06_APRENDIZAJE/LEARNING_INDEX.md";x=1680;y=280;width=360;height=220});edges=@(@{id="e1";fromNode="home";fromSide="right";toNode="control";toSide="left"},@{id="e2";fromNode="control";fromSide="right";toNode="contract";toSide="left"},@{id="e3";fromNode="contract";fromSide="right";toNode="tasks";toSide="left"},@{id="e4";fromNode="contract";fromSide="bottom";toNode="evidence";toSide="top"},@{id="e5";fromNode="evidence";fromSide="right";toNode="result";toSide="left"},@{id="e6";fromNode="result";fromSide="right";toNode="learning";toSide="left"})}
J (Join-Path $ModuleVault "07_CANVAS\MODULE_OPERATIVE_CANVAS.canvas") $canvas
L "OK module_vault_operationalized=True module_vault=$ModuleVault" Green
