param([string]$Mode="menu")
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$Root="C:\ENGREMIAT_CORE"
$Base="C:\Users\pc\Desktop\ENGREMIAT_OPERATOR"
$StatePath=Join-Path $Root "data\desktop-terminal-operator\operator-state.v1.json"
$ReportDir=Join-Path $Root "reports\functional-validation"
function W([string]$M,[string]$C="Gray"){ Write-Host $M -ForegroundColor $C }
function Box([string]$T,[object[]]$L,[string]$C="Cyan"){ W ""; W ("==== "+$T+" ====") $C; foreach($X in $L){ W ([string]$X) $C } }
function D([string]$P){ [System.IO.Directory]::CreateDirectory($P)|Out-Null }
function Back([string]$P="Enter para volver"){ [void](Read-Host $P) }
function Cmd([string]$P){ $V=Read-Host $P; if($null -eq $V){ return "" }; return ([string]$V).Trim().ToLowerInvariant() }
function SetP([object]$O,[string]$N,[object]$V){ if($O.PSObject.Properties.Name -contains $N){ $O.$N=$V } else { $O|Add-Member -NotePropertyName $N -NotePropertyValue $V -Force } }
function LoadJ([string]$P){ if(Test-Path -LiteralPath $P -PathType Leaf){ try { return (Get-Content -LiteralPath $P -Raw -Encoding UTF8|ConvertFrom-Json) } catch {} }; return [pscustomobject]@{} }
function SaveJ([object]$V,[string]$P){ D (Split-Path -Parent $P); $V|ConvertTo-Json -Depth 80|Set-Content -LiteralPath $P -Encoding UTF8 }
function ErrLog([string]$Where,[object]$E){ D $ReportDir; $P=Join-Path $ReportDir ("projects-manager-error-"+(Get-Date -Format "yyyyMMdd-HHmmss")+".json"); SaveJ ([ordered]@{where=$Where;message=$E.Exception.Message;exception=$E.Exception.ToString();script=$PSCommandPath;created_at=(Get-Date).ToString("s")}) $P; W ""; W ("ERR capturado en "+$Where) Red; W $E.Exception.Message Red; W ("LOG "+$P) Yellow; Back "Enter para continuar" }
function ActivePath{ if(!(Test-Path -LiteralPath $StatePath -PathType Leaf)){ return "" }; try { $S=Get-Content -LiteralPath $StatePath -Raw -Encoding UTF8|ConvertFrom-Json; foreach($K in @("active_project_path","current_project_path","active_project","current_project")){ if($S.PSObject.Properties.Name -contains $K){ $V=[string]$S.$K; if($V -and (Test-Path -LiteralPath $V)){ return (Resolve-Path -LiteralPath $V).Path } } } } catch {}; return "" }
function EnsurePJ([string]$P,[string]$Status){ if(!$P -or !(Test-Path -LiteralPath $P -PathType Container)){ return }; $Control=Join-Path $P "BOVEDA_PROYECTO\00_CONTROL"; D $Control; $Jp=Join-Path $Control "project.json"; $J=LoadJ $Jp; SetP $J "project_id" (Split-Path -Leaf $P); SetP $J "name" (Split-Path -Leaf $P); SetP $J "path" $P; SetP $J "status" $Status; SetP $J "operator_status" $Status; SetP $J "updated_at" ((Get-Date).ToString("s")); SaveJ $J $Jp }
function Projects{ if(!(Test-Path -LiteralPath $Base -PathType Container)){ return @() }; $A=ActivePath; $R=New-Object System.Collections.ArrayList; $Dirs=@(Get-ChildItem -LiteralPath $Base -Directory -Filter "ENGREMIAT_PROJECT_*" -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending); foreach($D0 in $Dirs){ $P=(Resolve-Path -LiteralPath $D0.FullName).Path; $S="HISTORICO"; if($A -ne "" -and $P -eq $A){ $S="ACTIVO" }; [void]$R.Add([pscustomobject]@{Name=$D0.Name;Path=$P;Status=$S;LastWriteTime=$D0.LastWriteTime}) }; return @($R) }
function SaveActive([string]$P){ if(!$P -or !(Test-Path -LiteralPath $P -PathType Container)){ throw "Proyecto no valido: $P" }; $R=(Resolve-Path -LiteralPath $P).Path; $S=LoadJ $StatePath; $N=Split-Path -Leaf $R; foreach($K in @("active_project","active_project_path","current_project","current_project_path")){ SetP $S $K $R }; SetP $S "active_project_name" $N; SetP $S "updated_at" ((Get-Date).ToString("s")); SetP $S "last_project_lifecycle_action" ([ordered]@{action="activate";project=$R;created_at=(Get-Date).ToString("s")}); SaveJ $S $StatePath; foreach($D0 in @(Get-ChildItem -LiteralPath $Base -Directory -Filter "ENGREMIAT_PROJECT_*" -ErrorAction SilentlyContinue)){ $DP=(Resolve-Path -LiteralPath $D0.FullName).Path; if($DP -eq $R){ EnsurePJ $DP "ACTIVO" } else { EnsurePJ $DP "HISTORICO" } } }
function Historic([string]$P){ $R=(Resolve-Path -LiteralPath $P).Path; EnsurePJ $R "HISTORICO"; if((ActivePath) -eq $R){ $S=LoadJ $StatePath; foreach($K in @("active_project","active_project_path","active_project_name","current_project","current_project_path")){ SetP $S $K "" }; SetP $S "updated_at" ((Get-Date).ToString("s")); SetP $S "last_project_lifecycle_action" ([ordered]@{action="historify_active";project=$R;created_at=(Get-Date).ToString("s")}); SaveJ $S $StatePath } }
function OpenF([string]$P){ if(Test-Path -LiteralPath $P){ Start-Process -FilePath "explorer.exe" -ArgumentList @($P)|Out-Null } else { Box "NO_GO" @("No existe: $P") Yellow; Back } }
function Workspace([object]$Pj){ while($true){ try { Clear-Host; Box "ESPACIO DE TRABAJO" @($Pj.Name,$Pj.Path,("Estado: "+$Pj.Status)) Cyan; W " [1] Carpeta del proyecto" Green; W " [2] Modulos del proyecto" Green; W " [3] Espacio modulo inicio" Green; W " [4] Control del proyecto" Yellow; W " [b] Atras" Yellow; W ""; W "Enter = refrescar | b = volver" DarkGray; $A=Cmd "PROYECTO"; if($A -eq ""){continue}; if($A -eq "b" -or $A -eq "q"){break}; if($A -eq "1"){OpenF $Pj.Path;continue}; if($A -eq "2"){ $Scr=Join-Path $Root "tools\desktop-terminal-operator\eng-project-modules-screen.ps1"; if(Test-Path -LiteralPath $Scr){ & powershell -NoProfile -ExecutionPolicy Bypass -File $Scr -ProjectPath $Pj.Path } else { Box "NO_GO" @("No existe pantalla: $Scr") Yellow; Back }; continue }; if($A -eq "3"){OpenF (Join-Path $Pj.Path "MODULOS\MODULE_inicio\BOVEDA_MODULO");continue}; if($A -eq "4"){OpenF (Join-Path $Pj.Path "BOVEDA_PROYECTO\00_CONTROL");continue}; W ("Comando no reconocido: "+$A) Yellow; Back } catch { ErrLog "Workspace" $_ } } }
function ShowHist{ while($true){ try { Clear-Host; $Ps=Projects; $H=@($Ps|Where-Object{$_.Status -ne "ACTIVO"}|Sort-Object LastWriteTime -Descending); Box "HISTORICO" @("numero = activar | oN = abrir carpeta | b = atras") Yellow; if($H.Count -eq 0){ W " Historico vacio." Yellow } else { for($I=0;$I -lt $H.Count;$I++){ W (" ["+($I+1)+"] "+$H[$I].Name+"  "+$H[$I].LastWriteTime.ToString("yyyy-MM-dd HH:mm")+"  HISTORICO") Gray } }; W ""; $A=Cmd "HISTORICO"; if($A -eq ""){continue}; if($A -eq "b" -or $A -eq "q"){break}; if($A -match "^o(\d+)$"){ $Idx=[int]$Matches[1]-1; if($Idx -ge 0 -and $Idx -lt $H.Count){OpenF $H[$Idx].Path}; continue }; $N=0; if([int]::TryParse($A,[ref]$N) -and $N -ge 1 -and $N -le $H.Count){SaveActive $H[$N-1].Path;break}; W ("Comando no reconocido: "+$A) Yellow; Back } catch { ErrLog "Historico" $_ } } }
function Help{ Clear-Host; Box "AYUDA PROYECTOS" @("numero = abrir espacio de trabajo activo","oN = abrir carpeta","hN = enviar activo a historico","v = historico","n = nuevo","b/q = salir") Cyan; Back }
function Maint{ Clear-Host; Box "MANTENIMIENTO" @("Captura minima de incidencia.") Yellow; $Sev=Read-Host "Severidad LOW/MEDIUM/HIGH/BLOCKER"; $Exp=Read-Host "Esperado"; $Obs=Read-Host "Observado / que falla"; $Act=Read-Host "Accion realizada antes del fallo"; if([string]::IsNullOrWhiteSpace($Sev)){$Sev="MEDIUM"}; $Dir=Join-Path $Root "reports\human-maintenance-cards"; D $Dir; $P=Join-Path $Dir ("human-maintenance-card-"+(Get-Date -Format "yyyyMMdd-HHmmss")+".json"); SaveJ ([ordered]@{severity=$Sev;expected=$Exp;observed=$Obs;action_before_failure=$Act;created_at=(Get-Date).ToString("s");source=$PSCommandPath}) $P; W ("OK tarjeta="+$P) Green; Back }
function Main{ while($true){ try { Clear-Host; W "Ruta: PROYECTOS ACTIVOS" Cyan; W "[?] Ayuda  [m] Mantenimiento  [Enter] Refrescar" DarkGray; W ""; Box "PROYECTOS ACTIVOS" @("numero = espacio de trabajo | oN = abrir carpeta | hN = historico | v = historico | n = nuevo | q = salir") Cyan; $Ps=Projects; $Acs=@($Ps|Where-Object{$_.Status -eq "ACTIVO"}|Sort-Object LastWriteTime -Descending); if($Acs.Count -eq 0){ W " No hay proyectos activos." Yellow } else { for($I=0;$I -lt $Acs.Count;$I++){ W (" ["+($I+1)+"] "+$Acs[$I].Name+"  "+$Acs[$I].LastWriteTime.ToString("yyyy-MM-dd HH:mm")+"  ACTIVO") Green } }; W ""; W "[v] Historico  [n] Nuevo  [q] Salir" Yellow; W ""; $A=Cmd "ENGREMIAT"; if($A -eq ""){continue}; if($A -eq "q" -or $A -eq "b"){break}; if($A -eq "?" -or $A -eq "h" -or $A -eq "help"){Help;continue}; if($A -eq "m"){Maint;continue}; if($A -eq "v"){ShowHist;continue}; if($A -eq "n"){ $Cr=Join-Path $Root "tools\desktop-terminal-operator\eng-new-project-safe.ps1"; if(Test-Path -LiteralPath $Cr){ & powershell -NoProfile -ExecutionPolicy Bypass -File $Cr; $Latest=@(Get-ChildItem -LiteralPath $Base -Directory -Filter "ENGREMIAT_PROJECT_*" -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 1); if($Latest.Count -gt 0){SaveActive $Latest[0].FullName} } else { Box "NO_GO" @("No encuentro creador: $Cr") Yellow; Back }; continue }; if($A -match "^o(\d+)$"){ $Idx=[int]$Matches[1]-1; if($Idx -ge 0 -and $Idx -lt $Acs.Count){OpenF $Acs[$Idx].Path}; continue }; if($A -match "^h(\d+)$"){ $Idx=[int]$Matches[1]-1; if($Idx -ge 0 -and $Idx -lt $Acs.Count){Historic $Acs[$Idx].Path}; continue }; $N=0; if([int]::TryParse($A,[ref]$N) -and $N -ge 1 -and $N -le $Acs.Count){Workspace $Acs[$N-1];continue}; W ("Comando no reconocido: "+$A) Yellow; Back } catch { ErrLog "Main" $_ } } }
Main
