$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()

# ENGREMIAT isolated subscreen routing adapter
# Generated by ENGREMIAT_SCREEN_NORMALIZER_SUBSCREEN_ROUTING_ADAPTER_001
# Safe mode: does not patch ENGREMIAT-LAUNCHER-ACTUAL.ps1

$Root = 'C:\ENGREMIAT_CORE'
$Screens = @(
    [pscustomobject]@{ id='PROYECTOS'; path='C:\ENGREMIAT_CORE\documents\screen-normalizer-internal-candidates-generation\generated\PROYECTOS.candidate.isolated.ps1'; sha256='F56F1F3C73F22CFFD5F6E6E5FFF1CA87EA97B8282B69CB656B13A1E013E7F465' },
    [pscustomobject]@{ id='MEMORIA_DOCUMENTACION'; path='C:\ENGREMIAT_CORE\documents\screen-normalizer-internal-candidates-generation\generated\MEMORIA_DOCUMENTACION.candidate.isolated.ps1'; sha256='CA09A41904F9C0FB923457DFC7BBEE8B1A7C05CD8668526915A3FED5F07A0C24' },
    [pscustomobject]@{ id='CONTROL_ESTADO'; path='C:\ENGREMIAT_CORE\documents\screen-normalizer-internal-candidates-generation\generated\CONTROL_ESTADO.candidate.isolated.ps1'; sha256='72E585DAC556CBC0B903F1B109814250F56E3CEC44D072C8997F601BD0049FEB' },
    [pscustomobject]@{ id='LAUNCHERS_CONFIGURACION'; path='C:\ENGREMIAT_CORE\documents\screen-normalizer-internal-candidates-generation\generated\LAUNCHERS_CONFIGURACION.candidate.isolated.ps1'; sha256='58608C17B1BCFDB421A6CF2122DA9F1CB6D79CFB2C92242217B8B6E294618F59' },
    [pscustomobject]@{ id='OPERADOR_WORKERS'; path='C:\ENGREMIAT_CORE\documents\screen-normalizer-internal-candidates-generation\generated\OPERADOR_WORKERS.candidate.isolated.ps1'; sha256='25BFF4B6AD3252F4CC180F094D8F81732AA865007B5FEB0CF8471D947FFD9E35' },
    [pscustomobject]@{ id='TARJETAS'; path='C:\ENGREMIAT_CORE\documents\screen-normalizer-internal-candidates-generation\generated\TARJETAS.candidate.isolated.ps1'; sha256='ADBACC220A4D00CE025211FD7436F08698913D42F1B6465DB0F731EAAAE6AD92' }
)

function Show-Menu {
  Clear-Host
  Write-Host "==== ENGREMIAT SUBSCREEN ROUTING ADAPTER ====" -ForegroundColor Cyan
  Write-Host "Ruta: INICIO > ADAPTER AISLADO > SUBPANTALLAS NORMALIZADAS" -ForegroundColor DarkGray
  Write-Host "Rol: probar navegacion a pantallas normalizadas sin tocar launcher general" -ForegroundColor DarkGray
  Write-Host "Estado: AISLADO / NO_PATCH" -ForegroundColor DarkGray
  Write-Host ""
  for($i=0;$i -lt $Screens.Count;$i++){ Write-Host (" [{0}] {1}" -f ($i+1),$Screens[$i].id) }
  Write-Host ""
  Write-Host "Enter = refrescar | ? = ayuda | q/b = salir" -ForegroundColor DarkGray
}

function Show-Help {
  Write-Host ""
  Write-Host "AYUDA" -ForegroundColor Cyan
  Write-Host "Este adapter ejecuta candidatos normalizados aislados."
  Write-Host "No modifica launchers reales, registry, git, red ni workers."
  Write-Host "Selecciona un numero para abrir una subpantalla candidata."
  Write-Host ""
}

while($true){
  Show-Menu
  $c = Read-Host "ENGREMIAT_ADAPTER"
  if([string]::IsNullOrWhiteSpace($c)){ continue }
  if($c -eq "q" -or $c -eq "b"){ break }
  if($c -eq "?"){ Show-Help; Read-Host "Enter"; continue }
  $n = 0
  if([int]::TryParse($c,[ref]$n) -and $n -ge 1 -and $n -le $Screens.Count){
    $s = $Screens[$n-1]
    Write-Host ("OPEN_SUBSCREEN screen={0} path={1}" -f $s.id,$s.path) -ForegroundColor Green
    & powershell -NoProfile -ExecutionPolicy Bypass -File $s.path
    Write-Host ""
    Read-Host "Enter para volver al adapter"
    continue
  }
  Write-Host "Comando no reconocido" -ForegroundColor Yellow
  Start-Sleep -Milliseconds 600
}