param([switch]$Json)
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function W($m,$c="Gray"){if(-not $Json){Write-Host $m -ForegroundColor $c}}
function TS($v){if($null -eq $v){return ""};return (($v|Out-String).Trim())}
function G($a){$out="$env:TEMP\eng_v1_memory_git_out.txt";$err="$env:TEMP\eng_v1_memory_git_err.txt";$p=Start-Process cmd.exe -ArgumentList ("/c git "+$a) -NoNewWindow -PassThru -Wait -RedirectStandardOutput $out -RedirectStandardError $err;[pscustomobject]@{ExitCode=$p.ExitCode;Stdout=(TS (Get-Content $out -Raw -ErrorAction SilentlyContinue));Stderr=(TS (Get-Content $err -Raw -ErrorAction SilentlyContinue))}}
function Get-MemoryItems($Root){ $items=@(); foreach($base in @("documents","data","reports")){ $full=Join-Path $Root $base; if(Test-Path $full){ Get-ChildItem $full -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in @(".md",".json",".txt") -and $_.Name -match "INDEX|CONTRACT|EVIDENCE|STATE|STATUS|NEXT|README|MANUAL|REPORT|\.md|\.json" } | Sort-Object LastWriteTime -Descending | Select-Object -First 160 | ForEach-Object { $kind="DOC"; if($_.Name -match "INDEX"){$kind="INDEX"} elseif($_.Name -match "CONTRACT"){$kind="CONTRACT"} elseif($_.Name -match "EVIDENCE|E[0-9]+_|REPORT"){$kind="EVIDENCE"} elseif($_.Name -match "STATE|STATUS|LATEST"){$kind="STATE"} elseif($_.Name -match "NEXT"){$kind="NEXT"} elseif($_.Name -match "README|MANUAL"){$kind="MANUAL"}; $items += [ordered]@{name=$_.Name;path=$_.FullName.Replace($Root+"\","");modified=$_.LastWriteTime.ToString("s");bytes=$_.Length;kind=$kind} } } }; return @($items) }
function Build-View($Root){ $Head=G "rev-parse --short HEAD"; $Branch=G "branch --show-current"; $Sync=G "rev-list --left-right --count origin/main...HEAD"; $Status=G "status --short"; $Items=Get-MemoryItems $Root; $IndexCount=($Items | Where-Object { $_.kind -eq "INDEX" }).Count; $ContractCount=($Items | Where-Object { $_.kind -eq "CONTRACT" }).Count; $EvidenceCount=($Items | Where-Object { $_.kind -eq "EVIDENCE" }).Count; $StateCount=($Items | Where-Object { $_.kind -eq "STATE" }).Count; $ManualCount=($Items | Where-Object { $_.kind -eq "MANUAL" }).Count; return [ordered]@{screen="OPERATOR_V1_MEMORY_DOCS";updated_at=(Get-Date).ToString("s");purpose="Pantalla V1 de memoria y documentacion con navegacion accionable read-only.";git=[ordered]@{branch=$Branch.Stdout;head=$Head.Stdout;rev_sync=$Sync.Stdout;tree_clean=[string]::IsNullOrWhiteSpace($Status.Stdout);status_short=$Status.Stdout};summary=[ordered]@{memory_items_count=$Items.Count;index_count=$IndexCount;contract_count=$ContractCount;evidence_count=$EvidenceCount;state_count=$StateCount;manual_count=$ManualCount;next_human_action="PROBAR_NUMERO_VER_DETALLE_READONLY_EN_MEMORY_DOCS_V1"};items=$Items;actions=[ordered]@{safe=@("numero_ver_detalle_readonly","Enter_refrescar","b_q_volver","ayuda");gated=@("abrir_documento_externo","editar_documento","generar_indice","modificar_memoria")};blocked_actions=@("abrir_documento_externo_sin_gate","editar_documento_sin_gate","generar_indice_sin_gate","modificar_memoria_sin_gate","push_auto","fetch_auto","merge_auto","delete_files","worker_real","api_externa","navegador","clipboard");next="E10_VALIDATE_ACTIONABLE_MEMORY_DOCS_AND_COMMIT_SCOPED"} }
$Root=(Get-Location).Path
$DetailViewer=Join-Path $Root "tools\operator-v1\operator-v1-detail-viewer-readonly.ps1"
$View=Build-View $Root
if($Json){$View | ConvertTo-Json -Depth 8; return}
while($true){ $View=Build-View $Root; Clear-Host; W "==== OPERADOR V1 / MEMORIA Y DOCUMENTACION ====" Cyan; W ("Actualizado: "+$View.updated_at) DarkGray; W ""; W "RESUMEN DOCUMENTAL" Cyan; W ("Elementos memoria/docs: "+$View.summary.memory_items_count) Green; W ("Indices: "+$View.summary.index_count+" | Contratos: "+$View.summary.contract_count+" | Evidencias: "+$View.summary.evidence_count) Gray; W ("Estado: "+$View.summary.state_count+" | Manuales/docs: "+$View.summary.manual_count) Gray; W ""; W "GIT" Cyan; W ("Branch:     "+$View.git.branch) Gray; W ("Head:       "+$View.git.head) Gray; W ("Rev sync:   "+$View.git.rev_sync) Gray; W ("Tree clean: "+$View.git.tree_clean) Gray; W ""; W "MEMORIA / DOCUMENTOS" Cyan; if($View.items.Count -eq 0){ W " - sin documentos candidatos" DarkYellow } else { $i=1; $View.items | Select-Object -First 24 | ForEach-Object { W (" ["+$i+"] ["+$_.kind+"] "+$_.path) Gray; $i++ } }; W ""; W "ACCIONES READONLY" Cyan; W " numero = ver detalle readonly | Enter/refrescar = redibujar | b/q = volver | ? = ayuda" Green; W ""; W "ACCIONES CON GATE / BLOQUEADAS" Cyan; $View.blocked_actions | ForEach-Object { W (" - "+$_) DarkYellow }; W ""; $cmd=Read-Host "MEMORIA"; if([string]::IsNullOrWhiteSpace($cmd) -or $cmd -eq "r" -or $cmd -eq "refrescar"){ continue }; if($cmd -eq "b" -or $cmd -eq "q" -or $cmd -eq "volver"){ break }; if($cmd -eq "?"){ W ""; W "Ayuda: escribe un numero para ver detalle readonly. No se abre documento externo ni se edita nada." Cyan; Read-Host "Enter" | Out-Null; continue }; $n=0; if([int]::TryParse($cmd,[ref]$n) -and $n -ge 1 -and $n -le $View.items.Count){ $item=$View.items[$n-1]; & powershell -NoProfile -ExecutionPolicy Bypass -File $DetailViewer -Title ("Memoria "+$n+": "+$item.name) -Kind $item.kind -Path $item.path; continue }; W "Comando no reconocido" DarkYellow; Start-Sleep -Milliseconds 700 }
