param([switch]$Json)
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function W($m,$c="Gray"){if(-not $Json){Write-Host $m -ForegroundColor $c}}
function TS($v){if($null -eq $v){return ""};return (($v|Out-String).Trim())}
function G($a){$out="$env:TEMP\eng_v1_data_git_out.txt";$err="$env:TEMP\eng_v1_data_git_err.txt";$p=Start-Process cmd.exe -ArgumentList ("/c git "+$a) -NoNewWindow -PassThru -Wait -RedirectStandardOutput $out -RedirectStandardError $err;[pscustomobject]@{ExitCode=$p.ExitCode;Stdout=(TS (Get-Content $out -Raw -ErrorAction SilentlyContinue));Stderr=(TS (Get-Content $err -Raw -ErrorAction SilentlyContinue))}}
function Get-DataItems($Root){ $items=@(); foreach($base in @("data","reports","documents","openwebui-knowledge")){ $full=Join-Path $Root $base; if(Test-Path $full){ Get-ChildItem $full -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in @(".json",".csv",".tsv",".txt",".md",".html") -or $_.FullName -match "intake|import|staging|source|dataset|sheet|csv|tsv|opendata|report" } | Sort-Object LastWriteTime -Descending | Select-Object -First 900 | ForEach-Object { $kind="DATA_FILE"; if($_.FullName -match "source|fuente"){$kind="SOURCE"} elseif($_.FullName -match "staging"){$kind="STAGING"} elseif($_.FullName -match "import"){$kind="IMPORT"} elseif($_.Extension -in @(".csv",".tsv")){$kind="SHEET_CSV_TSV"} elseif($_.FullName -match "report|reports"){$kind="REPORT"} elseif($_.Extension -eq ".json"){$kind="DATA_JSON"}; $items += [ordered]@{name=$_.Name;path=$_.FullName.Replace($Root+"\","");modified=$_.LastWriteTime.ToString("s");bytes=$_.Length;kind=$kind} } } }; return @($items) }
function Build-View($Root){ $Head=G "rev-parse --short HEAD"; $Branch=G "branch --show-current"; $Sync=G "rev-list --left-right --count origin/main...HEAD"; $Status=G "status --short"; $Items=Get-DataItems $Root; $SourceCount=($Items | Where-Object { $_.kind -eq "SOURCE" }).Count; $StagingCount=($Items | Where-Object { $_.kind -eq "STAGING" }).Count; $ImportCount=($Items | Where-Object { $_.kind -eq "IMPORT" }).Count; $SheetCount=($Items | Where-Object { $_.kind -eq "SHEET_CSV_TSV" }).Count; $ReportCount=($Items | Where-Object { $_.kind -eq "REPORT" }).Count; return [ordered]@{screen="OPERATOR_V1_DATA_INTAKE";updated_at=(Get-Date).ToString("s");purpose="Pantalla V1 de Data Intake con navegacion accionable read-only y gates prepare-only.";git=[ordered]@{branch=$Branch.Stdout;head=$Head.Stdout;rev_sync=$Sync.Stdout;tree_clean=[string]::IsNullOrWhiteSpace($Status.Stdout);status_short=$Status.Stdout};summary=[ordered]@{data_items_count=$Items.Count;source_count=$SourceCount;staging_count=$StagingCount;import_count=$ImportCount;sheet_csv_tsv_count=$SheetCount;report_count=$ReportCount;next_human_action="PROBAR_G1_GATE_PREVIEW_READONLY_EN_DATA_INTAKE_V1"};items=$Items;actions=[ordered]@{safe=@("numero_ver_detalle_readonly","gN_preparar_gate_readonly","gate_N_preparar_gate_readonly","Enter_refrescar","b_q_volver","ayuda");gated=@("preparar_importacion_fuente","validar_fuente","procesar_staging","exportar_dataset")};blocked_actions=@("importar_fuente_sin_gate","validar_fuente_sin_gate","procesar_staging_sin_gate","exportar_dataset_sin_gate","ejecutar_gate_sin_autorizacion","push_auto","fetch_auto","merge_auto","delete_files","worker_real","api_externa","navegador","clipboard");next="E13_VALIDATE_DATA_INTAKE_GATE_PREPARE_AND_COMMIT_SCOPED"} }
$Root=(Get-Location).Path
$DetailViewer=Join-Path $Root "tools\operator-v1\operator-v1-detail-viewer-readonly.ps1"
$GatePreviewer=Join-Path $Root "tools\operator-v1\operator-v1-gate-previewer-readonly.ps1"
$View=Build-View $Root
if($Json){$View | ConvertTo-Json -Depth 8; return}
while($true){ $View=Build-View $Root; Clear-Host; W "==== OPERADOR V1 / DATA INTAKE ====" Cyan; W ("Actualizado: "+$View.updated_at) DarkGray; W ""; W "RESUMEN DATA / INTAKE" Cyan; W ("Elementos data/intake: "+$View.summary.data_items_count) Green; W ("Fuentes: "+$View.summary.source_count+" | Staging: "+$View.summary.staging_count+" | Imports: "+$View.summary.import_count) Gray; W ("Sheets/CSV/TSV: "+$View.summary.sheet_csv_tsv_count+" | Reports: "+$View.summary.report_count) Gray; W ""; W "GIT" Cyan; W ("Branch:     "+$View.git.branch) Gray; W ("Head:       "+$View.git.head) Gray; W ("Rev sync:   "+$View.git.rev_sync) Gray; W ("Tree clean: "+$View.git.tree_clean) Gray; W ""; W "DATA / INTAKE / STAGING" Cyan; if($View.items.Count -eq 0){ W " - sin elementos data/intake" DarkYellow } else { $i=1; $View.items | Select-Object -First 24 | ForEach-Object { W (" ["+$i+"] ["+$_.kind+"] "+$_.path) Gray; $i++ } }; W ""; W "ACCIONES READONLY" Cyan; W " numero = ver detalle readonly | gN/gate N = preparar gate readonly | Enter/refrescar = redibujar | b/q = volver | ? = ayuda" Green; W ""; W "ACCIONES CON GATE / BLOQUEADAS" Cyan; $View.blocked_actions | ForEach-Object { W (" - "+$_) DarkYellow }; W ""; $cmd=Read-Host "DATA"; if([string]::IsNullOrWhiteSpace($cmd) -or $cmd -eq "r" -or $cmd -eq "refrescar"){ continue }; if($cmd -eq "b" -or $cmd -eq "q" -or $cmd -eq "volver"){ break }; if($cmd -eq "?"){ W ""; W "Ayuda: numero = detalle readonly. gN o gate N = preview de gate sin importar, validar, procesar ni exportar." Cyan; Read-Host "Enter" | Out-Null; continue }; $gateMatch=[regex]::Match($cmd,"^(g|gate)\s*(\d+)$",[System.Text.RegularExpressions.RegexOptions]::IgnoreCase); if($gateMatch.Success){ $n=[int]$gateMatch.Groups[2].Value; if($n -ge 1 -and $n -le $View.items.Count){ $item=$View.items[$n-1]; $gateId=("data_prepare_import_"+$n+"_"+$item.name).ToLower() -replace "[^a-z0-9]+","_"; & powershell -NoProfile -ExecutionPolicy Bypass -File $GatePreviewer -GateId $gateId -Screen "OPERATOR_V1_DATA_INTAKE" -ActionId "preparar_importacion_fuente" -Title ("Preparar importacion data "+$n+": "+$item.name) -Risk "HIGH" -TargetPath $item.path -CommandPreview ("PREVIEW_ONLY: Import/Validate/Stage "+$item.path+" -- NOT EXECUTED"); continue } }; $n2=0; if([int]::TryParse($cmd,[ref]$n2) -and $n2 -ge 1 -and $n2 -le $View.items.Count){ $item=$View.items[$n2-1]; & powershell -NoProfile -ExecutionPolicy Bypass -File $DetailViewer -Title ("Data "+$n2+": "+$item.name) -Kind $item.kind -Path $item.path; continue }; W "Comando no reconocido" DarkYellow; Start-Sleep -Milliseconds 700 }
