param([switch]$Json)
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function W($m,$c="Gray"){if(-not $Json){Write-Host $m -ForegroundColor $c}}
function TS($v){if($null -eq $v){return ""};return (($v|Out-String).Trim())}
function G($a){$out="$env:TEMP\eng_v1_memory_git_out.txt";$err="$env:TEMP\eng_v1_memory_git_err.txt";$p=Start-Process cmd.exe -ArgumentList ("/c git "+$a) -NoNewWindow -PassThru -Wait -RedirectStandardOutput $out -RedirectStandardError $err;[pscustomobject]@{ExitCode=$p.ExitCode;Stdout=(TS (Get-Content $out -Raw -ErrorAction SilentlyContinue));Stderr=(TS (Get-Content $err -Raw -ErrorAction SilentlyContinue))}}
function Get-MemoryItems($Root){ $items=@(); foreach($base in @("documents","obsidian","data","reports")){ $full=Join-Path $Root $base; if(Test-Path $full){ Get-ChildItem $full -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in @(".md",".json",".txt",".tsv",".csv") -or $_.FullName -match "index|contract|evidence|state|memory|memoria|operator-v1|operator-v2" } | Sort-Object LastWriteTime -Descending | Select-Object -First 480 | ForEach-Object { $kind="MEMORY_FILE"; if($_.Extension -eq ".md" -and $_.Name -match "INDEX|HOME|NEXT|README"){$kind="INDEX"} elseif($_.FullName -match "contract|CONTRACT"){$kind="CONTRACT"} elseif($_.FullName -match "evidence|report|reports"){$kind="EVIDENCE"} elseif($_.Extension -eq ".json"){$kind="DATA_JSON"} elseif($_.Extension -eq ".tsv" -or $_.Extension -eq ".csv"){$kind="TABLE"}; $items += [ordered]@{name=$_.Name;path=$_.FullName.Replace($Root+"\","");modified=$_.LastWriteTime.ToString("s");bytes=$_.Length;kind=$kind} } } }; return @($items) }
function Build-View($Root){ $Head=G "rev-parse --short HEAD"; $Branch=G "branch --show-current"; $Sync=G "rev-list --left-right --count origin/main...HEAD"; $Status=G "status --short"; $Items=Get-MemoryItems $Root; $IndexCount=($Items | Where-Object { $_.kind -eq "INDEX" }).Count; $ContractCount=($Items | Where-Object { $_.kind -eq "CONTRACT" }).Count; $EvidenceCount=($Items | Where-Object { $_.kind -eq "EVIDENCE" }).Count; return [ordered]@{screen="OPERATOR_V1_MEMORY_DOCS";updated_at=(Get-Date).ToString("s");purpose="Pantalla V1 de memoria/documentacion con navegacion accionable read-only y gates prepare-only.";git=[ordered]@{branch=$Branch.Stdout;head=$Head.Stdout;rev_sync=$Sync.Stdout;tree_clean=[string]::IsNullOrWhiteSpace($Status.Stdout);status_short=$Status.Stdout};summary=[ordered]@{memory_items_count=$Items.Count;index_count=$IndexCount;contract_count=$ContractCount;evidence_count=$EvidenceCount;next_human_action="PROBAR_G1_GATE_PREVIEW_READONLY_EN_MEMORY_DOCS_V1"};items=$Items;actions=[ordered]@{safe=@("numero_ver_detalle_readonly","gN_preparar_gate_readonly","gate_N_preparar_gate_readonly","Enter_refrescar","b_q_volver","ayuda");gated=@("abrir_documento_externo","crear_documento","editar_documento","indexar_documento")};blocked_actions=@("abrir_documento_externo_sin_gate","crear_documento_sin_gate","editar_documento_sin_gate","indexar_documento_sin_gate","ejecutar_gate_sin_autorizacion","push_auto","fetch_auto","merge_auto","delete_files","worker_real","api_externa","navegador","clipboard");next="E09_VALIDATE_MEMORY_DOCS_GATE_PREPARE_AND_COMMIT_SCOPED"} }
$Root=(Get-Location).Path
$DetailViewer=Join-Path $Root "tools\operator-v1\operator-v1-detail-viewer-readonly.ps1"
$GatePreviewer=Join-Path $Root "tools\operator-v1\operator-v1-gate-previewer-readonly.ps1"
$View=Build-View $Root
if($Json){$View | ConvertTo-Json -Depth 8; return}
while($true){ $View=Build-View $Root; Clear-Host; W "==== OPERADOR V1 / MEMORIA Y DOCUMENTACION ====" Cyan; W ("Actualizado: "+$View.updated_at) DarkGray; W ""; W "RESUMEN" Cyan; W ("Elementos memoria/docs: "+$View.summary.memory_items_count) Green; W ("Indices: "+$View.summary.index_count+" | Contratos: "+$View.summary.contract_count+" | Evidencias: "+$View.summary.evidence_count) Gray; W ""; W "GIT" Cyan; W ("Branch:     "+$View.git.branch) Gray; W ("Head:       "+$View.git.head) Gray; W ("Rev sync:   "+$View.git.rev_sync) Gray; W ("Tree clean: "+$View.git.tree_clean) Gray; W ""; W "MEMORIA / DOCUMENTACION" Cyan; if($View.items.Count -eq 0){ W " - sin documentos candidatos" DarkYellow } else { $i=1; $View.items | Select-Object -First 24 | ForEach-Object { W (" ["+$i+"] ["+$_.kind+"] "+$_.path) Gray; $i++ } }; W ""; W "ACCIONES READONLY" Cyan; W " numero = ver detalle readonly | gN/gate N = preparar gate readonly | Enter/refrescar = redibujar | b/q = volver | ? = ayuda" Green; W ""; W "ACCIONES CON GATE / BLOQUEADAS" Cyan; $View.blocked_actions | ForEach-Object { W (" - "+$_) DarkYellow }; W ""; $cmd=Read-Host "MEMORIA"; if([string]::IsNullOrWhiteSpace($cmd) -or $cmd -eq "r" -or $cmd -eq "refrescar"){ continue }; if($cmd -eq "b" -or $cmd -eq "q" -or $cmd -eq "volver"){ break }; if($cmd -eq "?"){ W ""; W "Ayuda: numero = detalle readonly. gN o gate N = preview de gate sin abrir ni modificar documentos." Cyan; Read-Host "Enter" | Out-Null; continue }; $gateMatch=[regex]::Match($cmd,"^(g|gate)\s*(\d+)$",[System.Text.RegularExpressions.RegexOptions]::IgnoreCase); if($gateMatch.Success){ $n=[int]$gateMatch.Groups[2].Value; if($n -ge 1 -and $n -le $View.items.Count){ $item=$View.items[$n-1]; $gateId=("memory_open_document_"+$n+"_"+$item.name).ToLower() -replace "[^a-z0-9]+","_"; & powershell -NoProfile -ExecutionPolicy Bypass -File $GatePreviewer -GateId $gateId -Screen "OPERATOR_V1_MEMORY_DOCS" -ActionId "abrir_documento_externo" -Title ("Abrir documento "+$n+": "+$item.name) -Risk "MEDIUM" -TargetPath $item.path -CommandPreview ("PREVIEW_ONLY: Start-Process "+$item.path+" -- NOT EXECUTED"); continue } }; $n2=0; if([int]::TryParse($cmd,[ref]$n2) -and $n2 -ge 1 -and $n2 -le $View.items.Count){ $item=$View.items[$n2-1]; & powershell -NoProfile -ExecutionPolicy Bypass -File $DetailViewer -Title ("Memoria "+$n2+": "+$item.name) -Kind $item.kind -Path $item.path; continue }; W "Comando no reconocido" DarkYellow; Start-Sleep -Milliseconds 700 }
