param([switch]$Json)
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function W($m,$c="Gray"){if(-not $Json){Write-Host $m -ForegroundColor $c}}
function TS($v){if($null -eq $v){return ""};return (($v|Out-String).Trim())}
function G($a){$out="$env:TEMP\eng_v1_health_git_out.txt";$err="$env:TEMP\eng_v1_health_git_err.txt";$p=Start-Process cmd.exe -ArgumentList ("/c git "+$a) -NoNewWindow -PassThru -Wait -RedirectStandardOutput $out -RedirectStandardError $err;[pscustomobject]@{ExitCode=$p.ExitCode;Stdout=(TS (Get-Content $out -Raw -ErrorAction SilentlyContinue));Stderr=(TS (Get-Content $err -Raw -ErrorAction SilentlyContinue))}}
function Get-HealthItems($Root){ $items=@(); foreach($base in @("tools","reports","documents","data","backups")){ $full=Join-Path $Root $base; if(Test-Path $full){ Get-ChildItem $full -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.FullName -match "health|launcher|smoke|repair|doctor|check|validate|operator-v1|operator-v2|screen" -or $_.Extension -in @(".ps1",".cmd",".bat",".json",".md",".txt") } | Sort-Object LastWriteTime -Descending | Select-Object -First 1200 | ForEach-Object { $kind="HEALTH_FILE"; if($_.FullName -match "launcher|ENGREMIAT\.ps1"){$kind="LAUNCHER"} elseif($_.FullName -match "smoke"){$kind="SMOKE"} elseif($_.FullName -match "repair|fix"){$kind="REPAIR"} elseif($_.FullName -match "doctor|health|check|validate"){$kind="HEALTHCHECK"} elseif($_.FullName -match "report|reports"){$kind="REPORT"} elseif($_.Extension -eq ".md"){$kind="DOC"} elseif($_.Extension -eq ".json"){$kind="DATA_JSON"}; $items += [ordered]@{name=$_.Name;path=$_.FullName.Replace($Root+"\","");modified=$_.LastWriteTime.ToString("s");bytes=$_.Length;kind=$kind} } } }; return @($items) }
function Build-View($Root){ $Head=G "rev-parse --short HEAD"; $Branch=G "branch --show-current"; $Sync=G "rev-list --left-right --count origin/main...HEAD"; $Status=G "status --short"; $Items=Get-HealthItems $Root; $LauncherCount=($Items | Where-Object { $_.kind -eq "LAUNCHER" }).Count; $SmokeCount=($Items | Where-Object { $_.kind -eq "SMOKE" }).Count; $RepairCount=($Items | Where-Object { $_.kind -eq "REPAIR" }).Count; $HealthCount=($Items | Where-Object { $_.kind -eq "HEALTHCHECK" }).Count; $ReportCount=($Items | Where-Object { $_.kind -eq "REPORT" }).Count; return [ordered]@{screen="OPERATOR_V1_HEALTH_LAUNCHERS";updated_at=(Get-Date).ToString("s");purpose="Pantalla V1 de Health Launchers con navegacion accionable read-only y gates prepare-only.";git=[ordered]@{branch=$Branch.Stdout;head=$Head.Stdout;rev_sync=$Sync.Stdout;tree_clean=[string]::IsNullOrWhiteSpace($Status.Stdout);status_short=$Status.Stdout};summary=[ordered]@{health_items_count=$Items.Count;launcher_count=$LauncherCount;smoke_count=$SmokeCount;repair_count=$RepairCount;healthcheck_count=$HealthCount;report_count=$ReportCount;next_human_action="PROBAR_G1_GATE_PREVIEW_READONLY_EN_HEALTH_LAUNCHERS_V1"};items=$Items;actions=[ordered]@{safe=@("numero_ver_detalle_readonly","gN_preparar_gate_readonly","gate_N_preparar_gate_readonly","Enter_refrescar","b_q_volver","ayuda");gated=@("preparar_ejecucion_healthcheck","preparar_ejecucion_smoke","preparar_ejecucion_repair","preparar_apertura_launcher")};blocked_actions=@("ejecutar_healthcheck_sin_gate","ejecutar_smoke_sin_gate","ejecutar_repair_sin_gate","abrir_launcher_sin_gate","ejecutar_gate_sin_autorizacion","push_auto","fetch_auto","merge_auto","delete_files","worker_real","api_externa","navegador","clipboard");next="E17_VALIDATE_HEALTH_LAUNCHERS_GATE_PREPARE_AND_COMMIT_SCOPED"} }
$Root=(Get-Location).Path
$DetailViewer=Join-Path $Root "tools\operator-v1\operator-v1-detail-viewer-readonly.ps1"
$GatePreviewer=Join-Path $Root "tools\operator-v1\operator-v1-gate-previewer-readonly.ps1"
$View=Build-View $Root
if($Json){$View | ConvertTo-Json -Depth 8; return}
while($true){ $View=Build-View $Root; Clear-Host; W "==== OPERADOR V1 / HEALTH LAUNCHERS ====" Cyan; W ("Actualizado: "+$View.updated_at) DarkGray; W ""; W "RESUMEN HEALTH / LAUNCHERS" Cyan; W ("Elementos health/launchers: "+$View.summary.health_items_count) Green; W ("Launchers: "+$View.summary.launcher_count+" | Smokes: "+$View.summary.smoke_count+" | Repairs: "+$View.summary.repair_count) Gray; W ("Healthchecks: "+$View.summary.healthcheck_count+" | Reports: "+$View.summary.report_count) Gray; W ""; W "GIT" Cyan; W ("Branch:     "+$View.git.branch) Gray; W ("Head:       "+$View.git.head) Gray; W ("Rev sync:   "+$View.git.rev_sync) Gray; W ("Tree clean: "+$View.git.tree_clean) Gray; W ""; W "HEALTH / LAUNCHERS / SMOKES" Cyan; if($View.items.Count -eq 0){ W " - sin elementos health/launchers" DarkYellow } else { $i=1; $View.items | Select-Object -First 24 | ForEach-Object { W (" ["+$i+"] ["+$_.kind+"] "+$_.path) Gray; $i++ } }; W ""; W "ACCIONES READONLY" Cyan; W " numero = ver detalle readonly | gN/gate N = preparar gate readonly | Enter/refrescar = redibujar | b/q = volver | ? = ayuda" Green; W ""; W "ACCIONES CON GATE / BLOQUEADAS" Cyan; $View.blocked_actions | ForEach-Object { W (" - "+$_) DarkYellow }; W ""; $cmd=Read-Host "HEALTH"; if([string]::IsNullOrWhiteSpace($cmd) -or $cmd -eq "r" -or $cmd -eq "refrescar"){ continue }; if($cmd -eq "b" -or $cmd -eq "q" -or $cmd -eq "volver"){ break }; if($cmd -eq "?"){ W ""; W "Ayuda: numero = detalle readonly. gN o gate N = preview de gate sin ejecutar healthcheck, smoke, repair ni launcher." Cyan; Read-Host "Enter" | Out-Null; continue }; $gateMatch=[regex]::Match($cmd,"^(g|gate)\s*(\d+)$",[System.Text.RegularExpressions.RegexOptions]::IgnoreCase); if($gateMatch.Success){ $n=[int]$gateMatch.Groups[2].Value; if($n -ge 1 -and $n -le $View.items.Count){ $item=$View.items[$n-1]; $risk="HIGH"; if($item.kind -eq "DOC" -or $item.kind -eq "REPORT" -or $item.kind -eq "DATA_JSON"){$risk="MEDIUM"}; $action="preparar_ejecucion_healthcheck"; if($item.kind -eq "SMOKE"){$action="preparar_ejecucion_smoke"} elseif($item.kind -eq "REPAIR"){$action="preparar_ejecucion_repair"} elseif($item.kind -eq "LAUNCHER"){$action="preparar_apertura_launcher"}; $gateId=("health_prepare_"+$n+"_"+$item.name).ToLower() -replace "[^a-z0-9]+","_"; & powershell -NoProfile -ExecutionPolicy Bypass -File $GatePreviewer -GateId $gateId -Screen "OPERATOR_V1_HEALTH_LAUNCHERS" -ActionId $action -Title ("Preparar accion health "+$n+": "+$item.name) -Risk $risk -TargetPath $item.path -CommandPreview ("PREVIEW_ONLY: Health/Smoke/Repair/Launcher "+$item.path+" -- NOT EXECUTED"); continue } }; $n2=0; if([int]::TryParse($cmd,[ref]$n2) -and $n2 -ge 1 -and $n2 -le $View.items.Count){ $item=$View.items[$n2-1]; & powershell -NoProfile -ExecutionPolicy Bypass -File $DetailViewer -Title ("Health "+$n2+": "+$item.name) -Kind $item.kind -Path $item.path; continue }; W "Comando no reconocido" DarkYellow; Start-Sleep -Milliseconds 700 }
