param([switch]$Json)
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function W($m,$c="Gray"){if(-not $Json){Write-Host $m -ForegroundColor $c}}
function TS($v){if($null -eq $v){return ""};return (($v|Out-String).Trim())}
function G($a){$out="$env:TEMP\eng_v1_projects_git_out.txt";$err="$env:TEMP\eng_v1_projects_git_err.txt";$p=Start-Process cmd.exe -ArgumentList ("/c git "+$a) -NoNewWindow -PassThru -Wait -RedirectStandardOutput $out -RedirectStandardError $err;[pscustomobject]@{ExitCode=$p.ExitCode;Stdout=(TS (Get-Content $out -Raw -ErrorAction SilentlyContinue));Stderr=(TS (Get-Content $err -Raw -ErrorAction SilentlyContinue))}}
function Get-ProjectCandidates($Root){ $items=@(); foreach($base in @("projects","data","documents")){ $full=Join-Path $Root $base; if(Test-Path $full){ Get-ChildItem $full -Directory -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 80 | ForEach-Object { if($_.Name -match "project|proyecto|operator-v1-projects|project-start-flow|builder|walkthrough|heartbeat"){ $kind="PROJECT_HINT"; if($_.FullName -match "\\projects\\"){$kind="PROJECT_DIR"} elseif($_.FullName -match "\\data\\"){$kind="PROJECT_DATA"} elseif($_.FullName -match "\\documents\\"){$kind="PROJECT_DOCS"}; $items += [ordered]@{name=$_.Name;path=$_.FullName.Replace($Root+"\","");modified=$_.LastWriteTime.ToString("s");kind=$kind} } } } }; return @($items) }
function Build-View($Root){ $Head=G "rev-parse --short HEAD"; $Branch=G "branch --show-current"; $Sync=G "rev-list --left-right --count origin/main...HEAD"; $Status=G "status --short"; $Projects=Get-ProjectCandidates $Root; $ActiveHint=($Projects | Where-Object { $_.name -match "active|actual|activo" }).Count; $HistoricHint=($Projects | Where-Object { $_.name -match "historic|history|historico|SIM_PROJECT" }).Count; return [ordered]@{screen="OPERATOR_V1_PROJECTS";updated_at=(Get-Date).ToString("s");purpose="Pantalla V1 de proyectos con navegacion accionable read-only.";git=[ordered]@{branch=$Branch.Stdout;head=$Head.Stdout;rev_sync=$Sync.Stdout;tree_clean=[string]::IsNullOrWhiteSpace($Status.Stdout);status_short=$Status.Stdout};summary=[ordered]@{project_candidates_count=$Projects.Count;active_hint_count=$ActiveHint;historic_hint_count=$HistoricHint;next_human_action="PROBAR_NUMERO_VER_DETALLE_READONLY_EN_PROJECTS_V1"};projects=$Projects;actions=[ordered]@{safe=@("numero_ver_detalle_readonly","Enter_refrescar","b_q_volver","ayuda");gated=@("abrir_carpeta_proyecto","crear_proyecto","activar_proyecto","archivar_proyecto")};blocked_actions=@("abrir_carpeta_sin_gate","crear_proyecto_sin_gate","activar_proyecto_sin_gate","archivar_proyecto_sin_gate","push_auto","fetch_auto","merge_auto","delete_files","worker_real","api_externa","navegador","clipboard");next="E06_VALIDATE_ACTIONABLE_PROJECTS_AND_COMMIT_SCOPED"} }
$Root=(Get-Location).Path
$DetailViewer=Join-Path $Root "tools\operator-v1\operator-v1-detail-viewer-readonly.ps1"
$View=Build-View $Root
if($Json){$View | ConvertTo-Json -Depth 8; return}
while($true){ $View=Build-View $Root; Clear-Host; W "==== OPERADOR V1 / PROYECTOS ====" Cyan; W ("Actualizado: "+$View.updated_at) DarkGray; W ""; W "RESUMEN" Cyan; W ("Proyectos candidatos: "+$View.summary.project_candidates_count) Green; W ("Activos hint: "+$View.summary.active_hint_count+" | Historicos hint: "+$View.summary.historic_hint_count) Gray; W ""; W "GIT" Cyan; W ("Branch:     "+$View.git.branch) Gray; W ("Head:       "+$View.git.head) Gray; W ("Rev sync:   "+$View.git.rev_sync) Gray; W ("Tree clean: "+$View.git.tree_clean) Gray; W ""; W "PROYECTOS" Cyan; if($View.projects.Count -eq 0){ W " - sin proyectos candidatos" DarkYellow } else { $i=1; $View.projects | Select-Object -First 20 | ForEach-Object { W (" ["+$i+"] ["+$_.kind+"] "+$_.path) Gray; $i++ } }; W ""; W "ACCIONES READONLY" Cyan; W " numero = ver detalle readonly | Enter/refrescar = redibujar | b/q = volver | ? = ayuda" Green; W ""; W "ACCIONES CON GATE / BLOQUEADAS" Cyan; $View.blocked_actions | ForEach-Object { W (" - "+$_) DarkYellow }; W ""; $cmd=Read-Host "PROYECTOS"; if([string]::IsNullOrWhiteSpace($cmd) -or $cmd -eq "r" -or $cmd -eq "refrescar"){ continue }; if($cmd -eq "b" -or $cmd -eq "q" -or $cmd -eq "volver"){ break }; if($cmd -eq "?"){ W ""; W "Ayuda: escribe un numero para ver detalle readonly. No se abre carpeta ni se ejecuta nada." Cyan; Read-Host "Enter" | Out-Null; continue }; $n=0; if([int]::TryParse($cmd,[ref]$n) -and $n -ge 1 -and $n -le $View.projects.Count){ $p=$View.projects[$n-1]; & powershell -NoProfile -ExecutionPolicy Bypass -File $DetailViewer -Title ("Proyecto "+$n+": "+$p.name) -Kind "PROJECT" -Path $p.path; continue }; W "Comando no reconocido" DarkYellow; Start-Sleep -Milliseconds 700 }
