param([string]$OutputPath="C:\ENGREMIAT_CORE\tools\context-guardian\TEMPLATE_GUARDED_PATCH_OPERATOR_V2.ps1")
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$lines=New-Object System.Collections.Generic.List[string]
$lines.Add('$ErrorActionPreference="Stop"')
$lines.Add('[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()')
$lines.Add('function W($m,$c="Gray"){Write-Host $m -ForegroundColor $c}')
$lines.Add('try{')
$lines.Add('  W "ENGREMIAT_PACKAGE_BEGIN package=<PACKAGE_ID> stage=<STAGE_ID>" Cyan')
$lines.Add('  $target="<TARGET_PATH>"')
$lines.Add('  $preflight="C:\ENGREMIAT_CORE\tools\context-guardian\Start-EngremiatGuardedWrite.ps1"')
$lines.Add('  $pf=& powershell -NoProfile -ExecutionPolicy Bypass -File $preflight -TargetPath $target -PackageId "<PACKAGE_ID>" -Stage "<STAGE_ID>" -Operation "<OPERATION>"')
$lines.Add('  $pfExit=$LASTEXITCODE')
$lines.Add('  W ($pf -join "`r`n") Gray')
$lines.Add('  if($pfExit -ne 0){throw "NO_GO_GUARDED_PREFLIGHT_EXIT=$pfExit"}')
$lines.Add('  $latest="C:\ENGREMIAT_CORE\reports\context-guardian-enforcement\guarded-write-preflight.latest.json"')
$lines.Add('  $guardReport=Get-ChildItem "C:\ENGREMIAT_CORE\reports\context-guardian-enforcement" -Filter "guarded-write-preflight-*.json"|Sort-Object LastWriteTime -Descending|Select-Object -First 1')
$lines.Add('  if(!$guardReport){throw "missing_guarded_write_report"}')
$lines.Add('  $g=Get-Content -LiteralPath $guardReport.FullName -Raw -Encoding UTF8|ConvertFrom-Json')
$lines.Add('  $backup=[string]$g.backup')
$lines.Add('  if(!(Test-Path -LiteralPath $backup)){throw "missing_backup_from_preflight"}')
$lines.Add('  $before=Get-Content -LiteralPath $target -Raw -Encoding UTF8')
$lines.Add('  # PATCH_BEGIN: sustituir este bloque por el cambio real')
$lines.Add('  $after=$before')
$lines.Add('  # PATCH_END')
$lines.Add('  if($after -eq $before){throw "PATCH_NO_CHANGE"}')
$lines.Add('  Set-Content -LiteralPath $target -Value $after -Encoding UTF8')
$lines.Add('  try{$null=[scriptblock]::Create((Get-Content -LiteralPath $target -Raw -Encoding UTF8))}catch{Copy-Item -LiteralPath $backup -Destination $target -Force;throw "PARSE_FAIL_RESTORED_BACKUP $($_.Exception.Message)"}')
$lines.Add('  W "OK guarded_patch_applied=True" Green')
$lines.Add('  W "OK target=$target" Green')
$lines.Add('  W "OK backup=$backup" DarkGray')
$lines.Add('  W "ENGREMIAT_PACKAGE_END package=<PACKAGE_ID> status=PASS" Cyan')
$lines.Add('}catch{')
$lines.Add('  W "ERR $($_.Exception.Message)" Red')
$lines.Add('  W "ENGREMIAT_PACKAGE_END package=<PACKAGE_ID> status=FAIL" Red')
$lines.Add('  throw')
$lines.Add('}')
$lines|Set-Content -LiteralPath $OutputPath -Encoding UTF8
try{$null=[scriptblock]::Create((Get-Content -LiteralPath $OutputPath -Raw -Encoding UTF8))}catch{throw "TEMPLATE_PARSE_FAIL $($_.Exception.Message)"}
Write-Host "OK guarded_patch_template_created=$OutputPath" -ForegroundColor Green
