param([string]$Mode="status",[string]$ResponseFile="")
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
function W($m,$c="Cyan"){Write-Host $m -ForegroundColor $c}
function D($p){if([string]::IsNullOrWhiteSpace($p)){return};if(-not(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Force -Path $p|Out-Null}}
function WL($p,[string[]]$a){D(Split-Path $p -Parent);Set-Content -LiteralPath $p -Value $a -Encoding UTF8}
function WJ($p,$o){D(Split-Path $p -Parent);$o|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $p -Encoding UTF8}
function RT($p){if(Test-Path -LiteralPath $p){return (Get-Content -LiteralPath $p -Raw -Encoding UTF8)};return ""}
$root=(Get-Location).Path
$gv=Join-Path $root "obsidian\ENGREMIAT_GLOBAL_VAULT"
$finalDraft=Join-Path $gv "07_BUNDLES\clean-ollama-openwebui-v2-final-draft"
$outbox=Join-Path $root "data\tool-calibration-controller\outbox"
$inbox=Join-Path $root "data\tool-calibration-controller\inbox"
$reports=Join-Path $root "reports\tool-calibration-controller"
D $outbox;D $inbox;D $reports
W "ENGREMIAT_PACKAGE_BEGIN package=ENGREMIAT_TOOL_CALIBRATION_CONTROLLER_SIMPLE mode=$Mode"
if($Mode -eq "status"){ $exists=Test-Path -LiteralPath $finalDraft; $files=@(); if($exists){$files=@(Get-ChildItem -LiteralPath $finalDraft -File -Filter "*.md"|Sort-Object Name|Select-Object -ExpandProperty Name)}; WJ (Join-Path $reports "controller-status-report.json") ([ordered]@{status="PASS";final_draft_exists=$exists;files=$files;analysis_only=$true;git=$false;network=$false;worker_real_execution=$false;auto_apply=$false;next=if($exists){"prepare"}else{"NO_GO_FINAL_DRAFT_MISSING"}}); W "OK controller_status=PASS final_draft_exists=$exists files=$($files.Count) next=prepare git=False network=False" Green }
elseif($Mode -eq "prepare"){ if(-not(Test-Path -LiteralPath $finalDraft)){throw "FINAL_DRAFT_NOT_FOUND $finalDraft"}; $packFiles=@(Get-ChildItem -LiteralPath $finalDraft -File -Filter "*.md"|Sort-Object Name|Select-Object -ExpandProperty FullName); $prompt=@("# CALIBRATION_RUN_PROMPT","","Objetivo: validar si el Knowledge/bundle responde de forma accionable, no generica.","","Criterios:","1. decision no vacia.","2. import_order_ok claro.","3. missing_context concreto o ninguno.","4. risks concretos.","5. first_safe_action distinta de acciones ya cerradas.","6. next_block exacto y ejecutable como nombre de paquete.","","Restricciones:","- analysis_only=true","- git=false","- network=false","- worker_real_execution=false","- auto_apply=false","- no modificar bundles originales","","Formato de respuesta:","decision:","quality_score_0_100:","generic_response: true|false","repeats_closed_step: true|false","missing_context:","risks:","first_safe_action:","next_block:","recommendation: ACCEPT|REDUCE|REFINE|NO_GO"); WL (Join-Path $outbox "CALIBRATION_RUN_PROMPT.md") $prompt; $list=@("# CALIBRATION FILES TO USE","","Final draft:",$finalDraft,"","Files:"); foreach($f in $packFiles){$list += $f}; WL (Join-Path $outbox "CALIBRATION_FILES_TO_USE.md") $list; Start-Process explorer.exe $finalDraft; Start-Process notepad.exe (Join-Path $outbox "CALIBRATION_RUN_PROMPT.md"); Start-Process notepad.exe (Join-Path $outbox "CALIBRATION_FILES_TO_USE.md"); WJ (Join-Path $reports "controller-prepare-report.json") ([ordered]@{status="PASS";mode="prepare";final_draft=$finalDraft;prompt=Join-Path $outbox "CALIBRATION_RUN_PROMPT.md";files=$packFiles;analysis_only=$true;git=$false;network=$false;worker_real_execution=$false;auto_apply=$false;next="paste_ai_response_to_file_then_run_intake"}); W "OK controller_prepare=PASS opened_final_draft=True calibration_prompt=True next=paste_ai_response_to_file_then_run_intake git=False network=False" Green }
elseif($Mode -eq "intake"){ if([string]::IsNullOrWhiteSpace($ResponseFile)){throw "RESPONSE_FILE_REQUIRED"}; if(-not(Test-Path -LiteralPath $ResponseFile)){throw "RESPONSE_FILE_NOT_FOUND $ResponseFile"}; $txt=RT $ResponseFile; $stamp=(Get-Date).ToString("yyyyMMdd-HHmmss"); $stored=Join-Path $inbox "calibration-response-$stamp.md"; WL $stored @("# CALIBRATION RESPONSE $stamp","",$txt); $hasNext=($txt -match "next_block\s*:"); $generic=($txt -match "No se especifica|No context explicitly|No concrete risks|No se mencionan riesgos"); $repeatsClosed=($txt -match "HOME|ESTADO|MASTER_INDEX|auditoria Obsidian|auditar"); $score=100; if(-not $hasNext){$score-=30}; if($generic){$score-=30}; if($repeatsClosed){$score-=20}; if($score -lt 0){$score=0}; $rec=if($score -ge 80){"ACCEPT"}elseif($score -ge 50){"REFINE"}else{"REDUCE"}; WJ (Join-Path $reports "controller-intake-report.json") ([ordered]@{status="PASS";response_file=$stored;quality_score_0_100=$score;generic_response=$generic;repeats_closed_step=$repeatsClosed;has_next_block=$hasNext;recommendation=$rec;analysis_only=$true;git=$false;network=$false;worker_real_execution=$false;auto_apply=$false;next=if($rec -eq "ACCEPT"){"MATERIALIZE_ACCEPTED_NEXT_BLOCK_PROPOSAL"}else{"REFINE_CALIBRATION_CONTEXT"}}); W "OK controller_intake=PASS quality_score=$score recommendation=$rec generic_response=$generic repeats_closed_step=$repeatsClosed git=False network=False" Green }
else{throw "UNKNOWN_MODE $Mode"}
W "ENGREMIAT_PACKAGE_END package=ENGREMIAT_TOOL_CALIBRATION_CONTROLLER_SIMPLE status=PASS" Green
