$ErrorActionPreference='Stop'
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$Core='C:\ENGREMIAT_CORE'
$Legacy=Join-Path $Core 'tools\launcher\ENGREMIAT-MEMORY-DOCUMENTATION-CENTER.ps1'
function W([string]$m,[string]$c='Gray'){try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function Pause(){Write-Host '';Read-Host '[Enter] volver / refrescar'|Out-Null}
function Header([string]$section=''){Clear-Host;W '==== MEMORIA Y DOCUMENTACION / CENTRO DOCUMENTAL ====' Cyan;W 'Ruta: INICIO > [15] Memoria y documentacion' DarkGray;W 'Rol: consumidor documental de fichas, memoria viva y salidas humanas' Gray;W 'Principio: Data Intake produce fichas; Centro Documental genera documentos' DarkGray;if($section){W $section Yellow};W ''}
function Legacy(){if(Test-Path $Legacy){& powershell -NoProfile -ExecutionPolicy Bypass -File $Legacy}else{W 'ERR legacy_no_encontrado' Red;Pause}}
function ShowSub([string]$title,[string[]]$items){while($true){Header $title;foreach($i in $items){W $i};W '';W '[l] abrir Centro Documental legacy funcional';W '[b] volver | [Enter] refrescar | ? = ayuda' DarkGray;W '';$op=Read-Host 'DOCUMENTACION_SUBMENU';switch($op){'l'{Legacy};'b'{return};''{continue};'?'{Header 'AYUDA';W 'Esta es una capa normalizada segura. Aun no sustituye handlers legacy.';W 'Usa [l] para abrir el Centro Documental funcional actual.';Pause};default{W 'Handler directo pendiente de cablear en siguiente fase. Usa [l] legacy.' Yellow;Start-Sleep -Milliseconds 900}}}}
function Menu(){while($true){Header;W '[1] Memoria viva';W '[2] Dossiers';W '[3] Convocatorias y fichas';W '[4] Contexto worker / continuidad';W '[5] Exportaciones y herramientas';W '[6] Carpetas y archivos';W '[7] Estado y ayuda';W '';W '[l] abrir Centro Documental actual funcional';W '[b] volver | [Enter] refrescar | ? = ayuda' DarkGray;W '';$op=Read-Host 'DOCUMENTACION';switch($op){'1'{ShowSub 'MEMORIA VIVA' @('[2] abrir memoria tecnica','[3] abrir resumen humano','[4] abrir informe de desarrollo')};'2'{ShowSub 'DOSSIERS' @('[5] abrir dossier subvenciones','[6] abrir dossier partners','[7] abrir dossier clientes','[15] generar dossier adaptado a convocatoria')};'3'{ShowSub 'CONVOCATORIAS Y FICHAS' @('[14] crear/editar ficha de convocatoria','[16] asistente rellenar ficha convocatoria','[17] Data Intake / Entrada de datos y fichas')};'4'{ShowSub 'CONTEXTO WORKER / CONTINUIDAD' @('[8] abrir contexto worker','[10] abrir contexto JSON')};'5'{ShowSub 'EXPORTACIONES Y HERRAMIENTAS' @('[11] exportar documentos DOCX/HTML con Pandoc','[12] abrir carpeta exports','[13] verificar herramientas documentales')};'6'{ShowSub 'CARPETAS Y ARCHIVOS' @('[9] abrir carpeta documents')};'7'{Header 'ESTADO Y AYUDA';W 'Normalizacion de pantalla creada como capa segura.' Green;W 'Siguiente fase: cablear handlers reales submenu por submenu.' Yellow;Pause};'l'{Legacy};'b'{return};''{continue};'?'{Header 'AYUDA';W 'Pantalla normalizada experimental. No rompe la pantalla legacy.';W 'Objetivo: ordenar antes de cablear handlers reales.';Pause};default{W 'Opcion no reconocida' Yellow;Start-Sleep -Milliseconds 700}}}}
Menu
