$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$Core="C:\ENGREMIAT_CORE"
function UX([string]$m,[string]$role="info"){$c=switch($role){"title"{"Cyan"}"route"{"DarkGray"}"role"{"Gray"}"principle"{"DarkGray"}"section"{"Yellow"}"ok"{"Green"}"warn"{"Yellow"}"err"{"Red"}"next"{"Cyan"}"muted"{"DarkGray"}default{"Gray"}};try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function W([string]$m,[string]$c="Gray"){try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function UXOk([string]$m){UX ("[OK] "+$m) "ok"}
function UXWarn([string]$m){UX ("[WARN] "+$m) "warn"}
function UXErr([string]$m){UX ("[ERR] "+$m) "err"}
function P(){Write-Host "";Read-Host "[Enter] volver / refrescar"|Out-Null}
function Header([string]$section=""){Clear-Host;UX "==== DATA INTAKE / ENTRADA DE DATOS Y FICHAS ====" "title";UX "Ruta: INICIO > Memoria y documentacion > Data Intake" "route";UX "Rol: productor y normalizador local de fichas estructuradas" "role";UX "Principio: Entrada de datos produce perfiles normalizados; Centro Documental consume fichas" "principle";if($section){UX $section "section"};Write-Host ""}
function EnsureDir([string]$p){New-Item -ItemType Directory -Force -Path $p|Out-Null}
function OpenPath([string]$p,[string]$title){EnsureDir $p;Start-Process explorer.exe $p;Header $title;UXOk ("abierto: "+$p);P}
function EnsureDemoProfile(){EnsureDir (Join-Path $Core "documents\grants");$p=Join-Path $Core "documents\grants\grant-call-profile-latest.json";if(!(Test-Path $p)){$o=[ordered]@{nombre_convocatoria="Convocatoria demo de innovacion social y economia circular";entidad_convocante="Entidad publica demo";territorio="Catalunya / España";fecha_limite="2026-12-31";objetivo_convocatoria="Financiar proyectos piloto con impacto social, economia circular y digitalizacion local.";lineas_prioritarias=@("Economia circular","Innovacion social","Digitalizacion local");importe_solicitado="50000 EUR";cofinanciacion="No requerida / pendiente de bases especificas";beneficiarios="Comunidades locales, entidades sociales y administraciones colaboradoras.";indicadores_requeridos=@("Personas beneficiarias","Tareas completadas","Evidencias documentadas");documentacion_requerida=@("Memoria tecnica","Presupuesto","Cronograma","Indicadores");criterios_valoracion=@("Innovacion social","Impacto medible","Viabilidad tecnica");tono="tecnico, claro, institucional y orientado a impacto";status="ready";human_review_required=$false;pending_fields=@()};$o|ConvertTo-Json -Depth 60|Set-Content $p -Encoding UTF8};Header "FICHA DEMO ACTIVA";UXOk ("ficha activa: "+$p);P}
function EditManualProfile(){EnsureDir (Join-Path $Core "documents\grants");$p=Join-Path $Core "documents\grants\grant-call-profile-latest.json";if(!(Test-Path $p)){EnsureDemoProfile};Start-Process notepad.exe $p;Header "FICHA MANUAL EDITABLE";UXOk ("abierto: "+$p);P}
function ImportTxtMd(){Header "IMPORTAR TXT/MD";UXWarn "Handler real pendiente de migrar desde launcher funcional legacy.";UX "Mantener legacy hasta migrar esta frontera." "muted";P}
function ImportJson(){Header "IMPORTAR JSON";UXWarn "Handler real pendiente de migrar desde launcher funcional legacy.";UX "Mantener legacy hasta migrar esta frontera." "muted";P}
function ShowStatus(){Header "ESTADO DATA INTAKE";$paths=@((Join-Path $Core "documents\intake\inbox"),(Join-Path $Core "documents\intake\normalized"),(Join-Path $Core "documents\intake\contracts"),(Join-Path $Core "documents\grants\grant-call-profile-latest.json"));foreach($p in $paths){if(Test-Path $p){UXOk $p}else{UXWarn ("MISS "+$p)}};P}
function ShowHelp(){Header "AYUDA DATA INTAKE";UX "Numeracion local por pantalla: usa [1]-[8]." "info";UX "b vuelve, Enter refresca, ? ayuda." "muted";UX "Las normas internas no se muestran en el header para reducir ruido." "muted";P}
function Menu(){while($true){Header;UX "[1] activar ficha demo completa" "info";UX "[2] crear/abrir ficha manual editable" "info";UX "[3] importar TXT/MD desde inbox y normalizar" "info";UX "[4] importar JSON desde inbox como ficha activa" "info";UX "[5] abrir carpeta inbox de entradas" "info";UX "[6] abrir carpeta normalized de fichas" "info";UX "[7] ver estado de Data Intake" "info";UX "[8] abrir contratos Data Intake" "info";Write-Host "";UX "[b] volver al Centro Documental | [Enter] refrescar | ? = ayuda" "muted";Write-Host "";$op=Read-Host "DATA_INTAKE";switch($op){"1"{EnsureDemoProfile};"2"{EditManualProfile};"3"{ImportTxtMd};"4"{ImportJson};"5"{OpenPath (Join-Path $Core "documents\intake\inbox") "INBOX DE ENTRADAS"};"6"{OpenPath (Join-Path $Core "documents\intake\normalized") "FICHAS NORMALIZED"};"7"{ShowStatus};"8"{OpenPath (Join-Path $Core "documents\intake\contracts") "CONTRATOS DATA INTAKE"};"b"{return};""{continue};"?"{ShowHelp};default{UXWarn "Opcion no reconocida";Start-Sleep -Milliseconds 700}}}}
Menu
