$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$Core="C:\ENGREMIAT_CORE"
$ProjectRoots=@((Join-Path $Core "projects"),"C:\Users\pc\Desktop\ENGREMIAT_OPERATOR","C:\Users\pc\Desktop")
function UX([string]$m,[string]$role="info"){$c=switch($role){"title"{"Cyan"}"route"{"DarkGray"}"role"{"Gray"}"principle"{"DarkGray"}"section"{"Yellow"}"ok"{"Green"}"warn"{"Yellow"}"err"{"Red"}"next"{"Cyan"}"muted"{"DarkGray"}default{"Gray"}};try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function UXOk([string]$m){UX ("[OK] "+$m) "ok"}
function UXWarn([string]$m){UX ("[WARN] "+$m) "warn"}
function P(){Write-Host "";Read-Host "[Enter] volver / refrescar"|Out-Null}
function Header([string]$section=""){Clear-Host;UX "==== PROYECTOS / CENTRO DE PROYECTOS ====" "title";UX "Ruta: INICIO > Proyectos" "route";UX "Rol: entrada humana principal para crear, abrir y operar proyectos" "role";UX "Principio: proyectos primero, modulos despues, legacy como respaldo" "principle";if($section){UX $section "section"};Write-Host ""}
function EnsureRoots(){foreach($r in $ProjectRoots){if($r -like (Join-Path $Core "projects")){New-Item -ItemType Directory -Force -Path $r|Out-Null}}}
function GetProjects(){EnsureRoots;$all=@();foreach($r in $ProjectRoots){if(Test-Path $r){$all+=Get-ChildItem $r -Directory -ErrorAction SilentlyContinue|Where-Object{$_.Name -match "^ENGREMIAT_PROJECT_" -or (Test-Path (Join-Path $_.FullName "MODULOS")) -or (Test-Path (Join-Path $_.FullName "project.json"))}}};$all|Sort-Object LastWriteTime -Descending -Unique}
function ShowProjects(){Header "PROYECTOS DISPONIBLES";$projects=@(GetProjects);if(!$projects.Count){UXWarn "No se han encontrado proyectos. Usa [3] crear proyecto minimo.";P;return};$i=1;foreach($p in $projects){$tag=if(Test-Path (Join-Path $p.FullName "project.json")){"ACTIVO/FORMAL"}elseif(Test-Path (Join-Path $p.FullName "MODULOS")){"CON_MODULOS"}else{"HISTORICO"};UX ("["+($i)+"] "+$p.Name+"  "+$p.LastWriteTime.ToString("yyyy-MM-dd HH:mm")+"  "+$tag);$i++};P}
function SelectProject(){Header "ABRIR PROYECTO";$projects=@(GetProjects);if(!$projects.Count){UXWarn "No hay proyectos detectados.";P;return};$i=1;foreach($p in $projects){UX ("["+($i)+"] "+$p.Name);$i++};Write-Host "";UX "[b] volver" "muted";$op=Read-Host "PROYECTO";if($op -eq "b"){return};$n=0;if(![int]::TryParse($op,[ref]$n) -or $n -lt 1 -or $n -gt $projects.Count){UXWarn "Seleccion no valida";Start-Sleep -Milliseconds 700;return};Start-Process explorer.exe $projects[$n-1].FullName;Header "PROYECTO ABIERTO";UXOk $projects[$n-1].FullName;P}
function NewProject(){Header "NUEVO PROYECTO MINIMO";$root=Join-Path $Core "projects";New-Item -ItemType Directory -Force -Path $root|Out-Null;$name=Read-Host "Nombre corto del proyecto";if(!$name -or !$name.Trim()){UXWarn "Cancelado: nombre vacio";P;return};$slug=($name.ToLowerInvariant() -replace "[^a-z0-9]+","-").Trim("-");if(!$slug){$slug="nuevo-proyecto"};$stamp=Get-Date -Format "yyyyMMdd-HHmmss";$dir=Join-Path $root ("ENGREMIAT_PROJECT_"+$slug+"_"+$stamp);New-Item -ItemType Directory -Force -Path $dir,(Join-Path $dir "MODULOS"),(Join-Path $dir "documents"),(Join-Path $dir "reports")|Out-Null;$obj=[ordered]@{id=("ENGREMIAT_PROJECT_"+$slug+"_"+$stamp);name=$name;created_at=(Get-Date).ToString("s");status="ACTIVE";source="PROJECTS_CENTER_NORMALIZED";modules_dir=(Join-Path $dir "MODULOS")};$obj|ConvertTo-Json -Depth 50|Set-Content (Join-Path $dir "project.json") -Encoding UTF8;Start-Process explorer.exe $dir;Header "PROYECTO CREADO";UXOk $dir;P}
function ProjectModules(){Header "MODULOS DEL PROYECTO";$projects=@(GetProjects);if(!$projects.Count){UXWarn "No hay proyectos detectados.";P;return};$i=1;foreach($p in $projects){UX ("["+($i)+"] "+$p.Name);$i++};Write-Host "";UX "[b] volver" "muted";$op=Read-Host "PROYECTO_MODULOS";if($op -eq "b"){return};$n=0;if(![int]::TryParse($op,[ref]$n) -or $n -lt 1 -or $n -gt $projects.Count){UXWarn "Seleccion no valida";Start-Sleep -Milliseconds 700;return};$mod=Join-Path $projects[$n-1].FullName "MODULOS";New-Item -ItemType Directory -Force -Path $mod|Out-Null;$mods=@(Get-ChildItem $mod -Directory -ErrorAction SilentlyContinue|Sort-Object Name);Header ("MODULOS / "+$projects[$n-1].Name);if(!$mods.Count){UXWarn "Sin modulos todavia.";UX ("Carpeta: "+$mod) "muted"}else{$j=1;foreach($m in $mods){UX ("["+($j)+"] "+$m.Name);$j++}};Write-Host "";UX "[o] abrir carpeta modulos | [Enter] volver" "muted";$x=Read-Host "MODULOS";if($x -eq "o"){Start-Process explorer.exe $mod}}
function OpenProjectsRoot(){EnsureRoots;$root=Join-Path $Core "projects";Start-Process explorer.exe $root;Header "CARPETA PROYECTOS";UXOk $root;P}
function Status(){Header "ESTADO PROYECTOS";EnsureRoots;$projects=@(GetProjects);UXOk ("proyectos_detectados="+$projects.Count);foreach($r in $ProjectRoots){if(Test-Path $r){UXOk $r}else{UXWarn ("no existe: "+$r)}};P}
function Help(){Header "AYUDA PROYECTOS";UX "Centro de proyectos normalizado.";UX "Primero se crea/abre proyecto; despues se gestionan modulos.";UX "No sustituye legacy: es pantalla paralela segura." "muted";P}
function Menu(){while($true){Header;UX "[1] ver proyectos";UX "[2] abrir proyecto";UX "[3] crear proyecto minimo";UX "[4] modulos del proyecto";UX "[5] abrir carpeta proyectos";UX "[6] estado y ayuda";Write-Host "";UX "[b] volver | [Enter] refrescar | ? = ayuda" "muted";Write-Host "";$op=Read-Host "PROYECTOS";switch($op){"1"{ShowProjects};"2"{SelectProject};"3"{NewProject};"4"{ProjectModules};"5"{OpenProjectsRoot};"6"{Status};"b"{return};""{continue};"?"{Help};default{UXWarn "Opcion no reconocida";Start-Sleep -Milliseconds 700}}}}
Menu
