param([string]$Root="C:\ENGREMIAT_CORE",[string]$Mode="audit")
$ErrorActionPreference="Stop"
function D($p){if(!(Test-Path $p)){New-Item -ItemType Directory -Force -Path $p|Out-Null}}
function ParseOk($p){if(!(Test-Path $p)){return $false};$errs=$null;$tok=$null;[System.Management.Automation.Language.Parser]::ParseFile($p,[ref]$tok,[ref]$errs)|Out-Null;return ($errs.Count -eq 0)}
$base=Join-Path $Root "documents\screen-master-template";$planned=Join-Path $base "planned";$reports=Join-Path $Root "reports\screen-master-template";D $planned;D $reports
$files=@();foreach($sr in @((Join-Path $Root "tools"),(Join-Path $Root "scripts"),(Join-Path $Root "src"))){if(Test-Path $sr){$files+=Get-ChildItem -Path $sr -Recurse -File -ErrorAction SilentlyContinue|Where-Object{$_.Extension -in @(".ps1",".psm1") -and $_.FullName -notmatch "\\node_modules\\|\\.git\\|\\reports\\|\\backups\\"}}}
$rows=@();foreach($f in ($files|Sort-Object FullName -Unique)){$txt=Get-Content $f.FullName -Raw -Encoding UTF8;$parse=ParseOk $f.FullName;$hasReadHost=$txt -match "Read-Host";$hasScreenText=$txt -match "====|Ruta:|\[[0-9]\]|Comando no reconocido|Enter = refrescar|PROYECTOS|INICIO|TARJETAS|MODULOS";$hasActionName=$f.FullName -match "add|safe|create|apply|repair|patch|worker|run|git|commit|backup";$hasWrites=$txt -match "Set-Content|Copy-Item|New-Item|Remove-Item|Move-Item|Out-File|Add-Content";$hasLoop=$txt -match "while\s*\(|switch\s*\(|do\s*\{|for\s*\(";$compressed=$txt -match "while\s*\(\$true\)\{.*Read-Host.*\}|switch\s*\(.*Read-Host.*\)";$hasEnter=$txt -match "IsNullOrWhiteSpace\([^\)]*\).*continue|Enter = refrescar";$hasB=$txt -match "`"b`"\s*\{|'b'\s*\{|\bb\s*=\s*volver|\[b/q\]";$hasQ=$txt -match "`"q`"\s*\{|'q'\s*\{|\bq\s*=\s*salir|\[b/q\]|b/q\s*=";$hasM=$txt -match "`"m`"\s*\{|'m'\s*\{|\bm\s*=\s*mantenimiento|mantenimiento";$hasHelp=$txt -match "`"\?`"\s*\{|'\?'\s*\{|\? = ayuda|\[\?\]\s*Ayuda";$templateScore=0;if($parse){$templateScore++};if($hasEnter){$templateScore++};if($hasB){$templateScore++};if($hasQ){$templateScore++};if($hasM){$templateScore++};if($hasHelp){$templateScore++};$screenScore=0;if($hasReadHost){$screenScore++};if($hasScreenText){$screenScore++};if($hasLoop){$screenScore++};$actionScore=0;if($hasActionName){$actionScore++};if($hasWrites){$actionScore++};if($hasReadHost -and -not $hasScreenText){$actionScore++};$kind="UNCLEAR";if($screenScore -ge 2 -and $screenScore -ge $actionScore){$kind="SCREEN_CANDIDATE"}elseif($actionScore -ge 2){$kind="ACTION_SCRIPT_WITH_PROMPTS"};$status="NEEDS_TEMPLATE";if($kind -eq "ACTION_SCRIPT_WITH_PROMPTS"){$status="EXCLUDE_ACTION"}elseif($templateScore -ge 6 -and -not $compressed){$status="READY"}elseif($templateScore -ge 4){$status="PARTIAL"};$strategy="MANUAL_REVIEW";if($status -eq "READY"){$strategy="VALIDATE_ONLY"}elseif($status -eq "EXCLUDE_ACTION"){$strategy="ACTION_PROMPT_CONTRACT"}elseif($compressed){$strategy="EXPAND_AND_REWRITE_BOUNDARY"}elseif($kind -eq "SCREEN_CANDIDATE"){$strategy="PREPARE_ROUTER_PATCH_NO_APPLY"};$rows+=[pscustomobject]@{path=$f.FullName;parse=$parse;kind=$kind;status=$status;strategy=$strategy;template_score=$templateScore;screen_score=$screenScore;action_score=$actionScore;compressed=$compressed;enter=$hasEnter;b=$hasB;q=$hasQ;m=$hasM;help=$hasHelp}}
$ready=@($rows|Where-Object{$_.status -eq "READY"});$partial=@($rows|Where-Object{$_.status -eq "PARTIAL"});$needs=@($rows|Where-Object{$_.status -eq "NEEDS_TEMPLATE"});$actions=@($rows|Where-Object{$_.status -eq "EXCLUDE_ACTION"});$nextTarget=$rows|Where-Object{$_.kind -eq "SCREEN_CANDIDATE" -and $_.status -ne "READY"}|Sort-Object @{Expression={if($_.strategy -eq "PREPARE_ROUTER_PATCH_NO_APPLY"){0}elseif($_.strategy -eq "EXPAND_AND_REWRITE_BOUNDARY"){1}else{2}}},template_score,path|Select-Object -First 1
$q=[ordered]@{generated_at=(Get-Date).ToString("s");mode=$Mode;total=$rows.Count;ready=$ready.Count;partial=$partial.Count;needs_template=$needs.Count;excluded_actions=$actions.Count;next_target=$nextTarget;rows=$rows};$queue=Join-Path $planned "screen-template-migration-queue.latest.json";$q|ConvertTo-Json -Depth 12|Set-Content -Encoding UTF8 $queue
$md=@("# Screen Template Migration Queue","","## Resumen","- total: "+$rows.Count,"- READY: "+$ready.Count,"- PARTIAL: "+$partial.Count,"- NEEDS_TEMPLATE: "+$needs.Count,"- EXCLUDE_ACTION: "+$actions.Count,"","## Next target",$(if($nextTarget){"- path: "+$nextTarget.path}else{"- NONE"}),$(if($nextTarget){"- strategy: "+$nextTarget.strategy}else{""}),"","| status | strategy | score | kind | compressed | path |","|---|---|---:|---|---|---|");foreach($r in ($rows|Sort-Object status,strategy,template_score,path)){$md+="| "+$r.status+" | "+$r.strategy+" | "+$r.template_score+" | "+$r.kind+" | "+$r.compressed+" | "+$r.path+" |"};$md|Set-Content -Encoding UTF8 (Join-Path $planned "screen-template-migration-queue.latest.md")
$rep=Join-Path $reports ("screen-template-migration-controller-"+$Mode+"-"+(Get-Date -Format "yyyyMMdd-HHmmss")+".json");$q|ConvertTo-Json -Depth 12|Set-Content -Encoding UTF8 $rep;Write-Host ("SCREEN_TEMPLATE_MIGRATION_CONTROLLER total="+$rows.Count+" ready="+$ready.Count+" partial="+$partial.Count+" needs="+$needs.Count+" actions="+$actions.Count) -ForegroundColor Cyan;if($nextTarget){Write-Host ("NEXT_TARGET="+$nextTarget.path) -ForegroundColor Yellow;Write-Host ("NEXT_STRATEGY="+$nextTarget.strategy) -ForegroundColor Yellow}else{Write-Host "NEXT_TARGET=NONE" -ForegroundColor Yellow};Write-Host ("QUEUE="+$queue) -ForegroundColor Green;Write-Host ("REPORT="+$rep) -ForegroundColor Green
