$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$Core="C:\ENGREMIAT_CORE"
$ProjectsRoot=Join-Path $Core "projects"
$ReportsDir=Join-Path $Core "reports\launcher"
$WorkerSyncDir=Join-Path $Core "documents\worker-sync"
function UX([string]$m,[string]$role="info"){ $c="Gray"; if($role -eq "title"){$c="Cyan"}elseif($role -eq "section"){$c="Yellow"}elseif($role -eq "ok"){$c="Green"}elseif($role -eq "warn"){$c="Yellow"}elseif($role -eq "err"){$c="Red"}elseif($role -eq "muted"){$c="DarkGray"}; try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m} }
function Header([string]$title,[string]$route,[string]$role,[string]$principle){Clear-Host;UX ("==== "+$title+" ====") "title";UX ("Ruta: "+$route) "muted";UX ("Rol: "+$role) "info";UX ("Principio: "+$principle) "muted";UX "" "info"}
function Short($s,[int]$n){$t=[string]$s;if([string]::IsNullOrWhiteSpace($t)){$t="-"};if($t.Length -le $n){return $t};if($n -le 3){return $t.Substring(0,$n)};return $t.Substring(0,$n-3)+"..."}
function Bar([int]$score,[string]$worker){$v=[Math]::Max(0,[Math]::Min(100,$score));$filled=[int][Math]::Floor($v/10);if($filled -gt 10){$filled=10};$empty=10-$filled;$core=("#"*$filled)+("-"*$empty);if($worker -eq "RUNNING" -and $filled -lt 10){$core=("#"*$filled)+">"+("-"*([Math]::Max(0,$empty-1)))};return "["+$core+"]"}
function ReadJsonSafe([string]$p){try{if(Test-Path $p){return Get-Content $p -Raw|ConvertFrom-Json}}catch{};return $null}
function GetLocalSignals(){[pscustomobject]@{heartbeat=(ReadJsonSafe (Join-Path $WorkerSyncDir "worker-heartbeat-latest.json"));project_signal=(ReadJsonSafe (Join-Path $WorkerSyncDir "project-signal-latest.json"))}}
function GetProjects(){New-Item -ItemType Directory -Force -Path $ProjectsRoot|Out-Null;@(Get-ChildItem $ProjectsRoot -Directory -ErrorAction SilentlyContinue|Where-Object{$_.Name -like "ENGREMIAT_PROJECT_*" -or (Test-Path (Join-Path $_.FullName "project.json"))}|Sort-Object LastWriteTime -Descending)}
function CountDirs([string]$p){try{return @(Get-ChildItem $p -Directory -ErrorAction SilentlyContinue).Count}catch{return 0}}
function CountFiles([string]$p){try{return @(Get-ChildItem $p -File -Recurse -ErrorAction SilentlyContinue).Count}catch{return 0}}
function MatchSignalForProject($project,$signals){$name=$project.Name;$path=$project.FullName;$candidates=@($signals.project_signal,$signals.heartbeat);foreach($s in $candidates){if($null -eq $s){continue};$sid=[string]$s.project_id;$spath=[string]$s.project_path;if($sid -and ($name -eq $sid -or $name -like ("*"+$sid+"*") -or $sid -like ("*"+$name+"*"))){return $s};if($spath -and $path -eq $spath){return $s}};return $null}
function DetectPhase($p){if(Test-Path (Join-Path $p.FullName "MODULOS")){return "MODULOS"};return "INICIO"}
function BaseSignal($p){$mods=CountDirs (Join-Path $p.FullName "MODULOS");$files=CountFiles $p.FullName;$score=20;if($mods -gt 0){$score+=40};if($files -gt 5){$score+=20};$block="WARN";$cause="generar evidencia";if($mods -gt 0 -and $files -gt 5){$block="OK";$cause="estructura minima"};[pscustomobject]@{name=$p.Name;phase=(DetectPhase $p);score=$score;worker="IDLE";block=$block;next=$cause;cause=$cause;signal_source="local"}}
function ApplySignal($sig,$tmp){if($null -eq $sig){return $tmp};if($sig.PSObject.Properties.Name -contains "phase" -and $sig.phase){$tmp.phase=[string]$sig.phase};if($sig.PSObject.Properties.Name -contains "progress_pct" -and $null -ne $sig.progress_pct){$tmp.score=[int]$sig.progress_pct};if($sig.PSObject.Properties.Name -contains "state" -and $sig.state){$tmp.worker=[string]$sig.state};if($sig.PSObject.Properties.Name -contains "next_action" -and $sig.next_action){$tmp.next=[string]$sig.next_action};if($sig.PSObject.Properties.Name -contains "blocked_reason" -and $sig.blocked_reason){$tmp.block="BLOCK";$tmp.cause=[string]$sig.blocked_reason}elseif($sig.PSObject.Properties.Name -contains "block" -and $sig.block){$tmp.block=[string]$sig.block;if($tmp.block -eq "OK"){$tmp.cause="signal_ok"}}elseif($tmp.worker -eq "RUNNING" -or $tmp.worker -eq "DONE"){$tmp.block="OK";$tmp.cause="live_signal_no_blocked_reason"};$tmp.signal_source="heartbeat";return $tmp}
function ProjectSignal($p,$signals){$tmp=BaseSignal $p;$sig=MatchSignalForProject $p $signals;return ApplySignal $sig $tmp}
function ShowProjects(){Header "PROYECTOS / CENTRO DE PROYECTOS" "INICIO > Proyectos" "entrada humana principal para ver cartera, workers y bloqueos" "tabla operativa con progreso visual y senales de worker";UX "CARTERA DE PROYECTOS / PROCESO VIVO" "section";UX "" "info";$items=@(GetProjects);$localSignals=GetLocalSignals;$rows=New-Object System.Collections.Generic.List[object];foreach($p in $items){$rows.Add((ProjectSignal $p $localSignals))};$total=$rows.Count;$ok=@($rows|Where-Object{$_.block -eq "OK"}).Count;$warn=@($rows|Where-Object{$_.block -eq "WARN"}).Count;$block=@($rows|Where-Object{$_.block -eq "BLOCK"}).Count;$run=@($rows|Where-Object{$_.worker -eq "RUNNING"}).Count;$wait=@($rows|Where-Object{$_.worker -eq "WAITING_HUMAN"}).Count;UX ("Total={0}  OK={1}  WARN={2}  BLOCK={3}  RUN={4}  WAIT={5}" -f $total,$ok,$warn,$block,$run,$wait) "info";UX "" "info";UX "N  NOMBRE                               FASE            PROGRESO     WORKER  BLOQ  NEXT" "section";$i=1;foreach($s in $rows){$line=("{0,2} {1,-36} {2,-15} {3} {4,-7} {5,-5} {6}" -f $i,(Short $s.name 36),(Short $s.phase 15),(Bar $s.score $s.worker),(Short $s.worker 7),(Short $s.block 5),(Short $s.next 28));if($s.block -eq "BLOCK"){UX $line "err"}elseif($s.worker -eq "RUNNING"){UX $line "ok"}elseif($s.block -eq "WARN"){UX $line "warn"}else{UX $line "info"};$i++};UX "" "info";UX "Enter refresca. RUNNING se infiere por heartbeat/project-signal local; Obsidian solo visualiza Markdown/YAML." "muted";Read-Host "PROYECTOS"}
function NewProject(){New-Item -ItemType Directory -Force -Path $ProjectsRoot|Out-Null;$name=Read-Host "Nombre proyecto";if([string]::IsNullOrWhiteSpace($name)){return};$safe=($name -replace "[^a-zA-Z0-9_-]","-").ToLower();$dir=Join-Path $ProjectsRoot ("ENGREMIAT_PROJECT_"+$safe+"_"+(Get-Date -Format "yyyyMMdd-HHmmss"));New-Item -ItemType Directory -Force -Path $dir,(Join-Path $dir "MODULOS"),(Join-Path $dir "documents"),(Join-Path $dir "reports")|Out-Null;[ordered]@{id=(Split-Path $dir -Leaf);name=$name;created_at=(Get-Date).ToString("s");status="ACTIVE"}|ConvertTo-Json -Depth 50|Set-Content (Join-Path $dir "project.json") -Encoding UTF8;UX ("OK proyecto creado: "+$dir) "ok";Read-Host "Enter"}
function OpenProjectsRoot(){New-Item -ItemType Directory -Force -Path $ProjectsRoot|Out-Null;Start-Process explorer.exe $ProjectsRoot}
function Status(){Header "PROYECTOS / ESTADO" "INICIO > Proyectos > Estado" "diagnostico local" "sin acciones externas";UX ("ProjectsRoot: "+$ProjectsRoot) "info";UX ("WorkerSyncDir: "+$WorkerSyncDir) "info";UX ("Projects: "+@(GetProjects).Count) "info";Read-Host "ESTADO"}
function Help(){Header "PROYECTOS / AYUDA" "INICIO > Proyectos > Ayuda" "ayuda contextual" "Enter refresca, b vuelve";UX "[1] ver cartera viva de proyectos" "info";UX "[2] crear proyecto minimo" "info";UX "[3] abrir carpeta proyectos" "info";UX "[4] estado" "info";UX "[b] volver/salir" "info";Read-Host "AYUDA"}
function Menu(){while($true){Header "PROYECTOS / CENTRO DE PROYECTOS" "INICIO > Proyectos" "entrada humana principal para crear, abrir y operar proyectos" "proyectos primero, modulos despues, heartbeat local como senal viva";UX "[1] ver cartera viva de proyectos" "section";UX "[2] crear proyecto minimo" "section";UX "[3] abrir carpeta proyectos" "section";UX "[4] estado y ayuda" "section";UX "[b] volver | [Enter] refrescar | ? = ayuda" "muted";$op=Read-Host "PROYECTOS";if([string]::IsNullOrWhiteSpace($op)){continue};if($op -eq "1"){ShowProjects}elseif($op -eq "2"){NewProject}elseif($op -eq "3"){OpenProjectsRoot}elseif($op -eq "4" -or $op -eq "?"){Help}elseif($op -eq "b" -or $op -eq "q"){break}else{UX "opcion no reconocida" "warn";Start-Sleep -Milliseconds 700}}}
Menu

