$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$Core="C:\ENGREMIAT_CORE"
function UX([string]$m,[string]$role="info"){$c=switch($role){"title"{"Cyan"}"route"{"DarkGray"}"role"{"Gray"}"principle"{"DarkGray"}"section"{"Yellow"}"ok"{"Green"}"warn"{"Yellow"}"err"{"Red"}"next"{"Cyan"}"muted"{"DarkGray"}default{"Gray"}};try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function W([string]$m,[string]$c="Gray"){try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function UXOk([string]$m){UX ("[OK] "+$m) "ok"}
function UXWarn([string]$m){UX ("[WARN] "+$m) "warn"}
function UXErr([string]$m){UX ("[ERR] "+$m) "err"}
function P(){Write-Host "";Read-Host "[Enter] volver / refrescar"|Out-Null}
function Header([string]$section=""){Clear-Host;UX "==== DATA INTAKE / ENTRADA DE DATOS Y FICHAS ====" "title";UX "Ruta: INICIO > Memoria y documentacion > Data Intake" "route";UX "Rol: productor y normalizador local de fichas estructuradas" "role";UX "Principio: Entrada de datos produce perfiles normalizados; Centro Documental consume fichas" "principle";if($section){UX $section "section"};Write-Host ""}
function EnsureDir([string]$p){New-Item -ItemType Directory -Force -Path $p|Out-Null}
function IntakeInbox(){return (Join-Path $Core "documents\intake\inbox")}
function IntakeNormalized(){return (Join-Path $Core "documents\intake\normalized")}
function IntakeContracts(){return (Join-Path $Core "documents\intake\contracts")}
function GrantsDir(){return (Join-Path $Core "documents\grants")}
function ActiveProfilePath(){EnsureDir (GrantsDir);return (Join-Path (GrantsDir) "grant-call-profile-latest.json")}
function OpenPath([string]$p,[string]$title){EnsureDir $p;Start-Process explorer.exe $p;Header $title;UXOk ("abierto: "+$p);P}
function NewDemoObject(){return [ordered]@{nombre_convocatoria="Convocatoria demo de innovacion social y economia circular";entidad_convocante="Entidad publica demo";territorio="Catalunya / España";fecha_limite="2026-12-31";objetivo_convocatoria="Financiar proyectos piloto con impacto social, economia circular y digitalizacion local.";lineas_prioritarias=@("Economia circular","Innovacion social","Digitalizacion local");importe_solicitado="50000 EUR";cofinanciacion="No requerida / pendiente de bases especificas";beneficiarios="Comunidades locales, entidades sociales y administraciones colaboradoras.";indicadores_requeridos=@("Personas beneficiarias","Tareas completadas","Evidencias documentadas");documentacion_requerida=@("Memoria tecnica","Presupuesto","Cronograma","Indicadores");criterios_valoracion=@("Innovacion social","Impacto medible","Viabilidad tecnica");tono="tecnico, claro, institucional y orientado a impacto";status="ready";human_review_required=$false;pending_fields=@();source_type="demo";normalized_by="DATA_INTAKE_NORMALIZED"}}
function SaveProfile($obj,[string]$sourceType,[string]$sourcePath){EnsureDir (IntakeNormalized);EnsureDir (GrantsDir);$stamp=Get-Date -Format "yyyyMMdd-HHmmss";$safe=$sourceType.ToLowerInvariant().Replace("/","-");$version=Join-Path (IntakeNormalized) ("grant-call-profile-from-"+$safe+"-"+$stamp+".json");$latest=Join-Path (IntakeNormalized) ("grant-call-profile-from-"+$safe+"-latest.json");$active=ActiveProfilePath;if($obj -isnot [System.Collections.IDictionary]){$obj=[ordered]@{raw=$obj}};$obj.source_type=$sourceType;$obj.source_path=$sourcePath;$obj.normalized_at=(Get-Date).ToString("s");$obj.normalized_by="DATA_INTAKE_NORMALIZED";$obj.status="ready";$obj.human_review_required=$false;if($null -eq $obj.pending_fields){$obj.pending_fields=@()};$obj|ConvertTo-Json -Depth 80|Set-Content $latest -Encoding UTF8;Copy-Item $latest $version -Force;Copy-Item $latest $active -Force;$repDir=Join-Path $Core "reports\launcher";EnsureDir $repDir;$rep=Join-Path $repDir ("data-intake-normalized-import-"+$safe+"-"+$stamp+".json");[pscustomobject]@{status="PASS";source_type=$sourceType;source_path=$sourcePath;latest=$latest;version=$version;active_profile=$active}|ConvertTo-Json -Depth 80|Set-Content $rep -Encoding UTF8;return [ordered]@{latest=$latest;version=$version;active=$active;report=$rep}}
function EnsureDemoProfile(){$res=SaveProfile (NewDemoObject) "demo" "internal-demo";Header "FICHA DEMO ACTIVA";UXOk ("ficha activa: "+$res.active);UXOk ("normalized: "+$res.latest);UXOk ("report: "+$res.report);P}
function EditManualProfile(){if(!(Test-Path (ActiveProfilePath))){$null=SaveProfile (NewDemoObject) "manual-seed" "internal-demo"};$p=ActiveProfilePath;Start-Process notepad.exe $p;Header "FICHA MANUAL EDITABLE";UXOk ("abierto: "+$p);P}
function ExtractValue([string]$text,[string[]]$keys,[string]$fallback){foreach($k in $keys){$m=[regex]::Match($text,"(?im)^\s*"+[regex]::Escape($k)+"\s*[:=]\s*(.+)$");if($m.Success){return $m.Groups[1].Value.Trim()}};return $fallback}
function ImportTxtMd(){EnsureDir (IntakeInbox);$files=@(Get-ChildItem (IntakeInbox) -File -Include *.txt,*.md -Recurse -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending);if(!$files.Count){Header "IMPORTAR TXT/MD";UXWarn ("No hay TXT/MD en inbox: "+(IntakeInbox));Start-Process explorer.exe (IntakeInbox);P;return};$f=$files|Select-Object -First 1;$txt=Get-Content $f.FullName -Raw;$obj=[ordered]@{nombre_convocatoria=ExtractValue $txt @("nombre_convocatoria","convocatoria","titulo","title") "Convocatoria importada desde TXT/MD";entidad_convocante=ExtractValue $txt @("entidad_convocante","entidad","convocante") "Entidad pendiente de revisar";territorio=ExtractValue $txt @("territorio","ambito","ámbito") "Territorio pendiente de revisar";fecha_limite=ExtractValue $txt @("fecha_limite","deadline","plazo","fecha") "Fecha pendiente de revisar";objetivo_convocatoria=ExtractValue $txt @("objetivo_convocatoria","objetivo","resumen") (($txt.Substring(0,[Math]::Min(400,$txt.Length))).Trim());lineas_prioritarias=@("Pendiente de revisar desde TXT/MD");importe_solicitado=ExtractValue $txt @("importe_solicitado","importe","presupuesto") "Importe pendiente de revisar";cofinanciacion=ExtractValue $txt @("cofinanciacion","cofinanciación") "Cofinanciacion pendiente de revisar";beneficiarios=ExtractValue $txt @("beneficiarios","destinatarios") "Beneficiarios pendientes de revisar";indicadores_requeridos=@("Pendiente de revisar");documentacion_requerida=@("Pendiente de revisar");criterios_valoracion=@("Pendiente de revisar");tono="tecnico, claro, institucional y orientado a impacto";confidence="medium";raw_excerpt=$txt.Substring(0,[Math]::Min(1200,$txt.Length))};$res=SaveProfile $obj "txt-md" $f.FullName;Header "TXT/MD IMPORTADO Y NORMALIZADO";UXOk ("source: "+$f.FullName);UXOk ("active_profile: "+$res.active);UXOk ("normalized: "+$res.latest);UXOk ("report: "+$res.report);P}
function ImportJson(){EnsureDir (IntakeInbox);$files=@(Get-ChildItem (IntakeInbox) -File -Filter *.json -Recurse -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending);if(!$files.Count){Header "IMPORTAR JSON";UXWarn ("No hay JSON en inbox: "+(IntakeInbox));Start-Process explorer.exe (IntakeInbox);P;return};$f=$files|Select-Object -First 1;try{$obj=Get-Content $f.FullName -Raw|ConvertFrom-Json -AsHashtable}catch{Header "IMPORTAR JSON";UXErr ("JSON invalido: "+$f.FullName);UXErr $_.Exception.Message;P;return};$res=SaveProfile $obj "json" $f.FullName;Header "JSON IMPORTADO COMO FICHA ACTIVA";UXOk ("source: "+$f.FullName);UXOk ("active_profile: "+$res.active);UXOk ("normalized: "+$res.latest);UXOk ("report: "+$res.report);P}
function ShowStatus(){Header "ESTADO DATA INTAKE";$paths=@((IntakeInbox),(IntakeNormalized),(IntakeContracts),(ActiveProfilePath));foreach($p in $paths){if(Test-Path $p){UXOk $p}else{UXWarn ("MISS "+$p)}};$profiles=@();if(Test-Path (IntakeNormalized)){$profiles=@(Get-ChildItem (IntakeNormalized) -Filter *.json -File|Sort-Object LastWriteTime -Descending|Select-Object -First 5)};UX ("Perfiles normalizados recientes: "+$profiles.Count) "info";foreach($p in $profiles){UX ("- "+$p.Name) "muted"};P}
function ShowHelp(){Header "AYUDA DATA INTAKE";UX "Usa [3] para tomar el TXT/MD mas reciente del inbox y convertirlo en ficha activa." "info";UX "Usa [4] para tomar el JSON mas reciente del inbox y convertirlo en ficha activa." "info";UX "b vuelve, Enter refresca, ? ayuda." "muted";P}
function Menu(){while($true){Header;UX "[1] activar ficha demo completa" "info";UX "[2] crear/abrir ficha manual editable" "info";UX "[3] importar TXT/MD desde inbox y normalizar" "info";UX "[4] importar JSON desde inbox como ficha activa" "info";UX "[5] abrir carpeta inbox de entradas" "info";UX "[6] abrir carpeta normalized de fichas" "info";UX "[7] ver estado de Data Intake" "info";UX "[8] abrir contratos Data Intake" "info";Write-Host "";UX "[b] volver al Centro Documental | [Enter] refrescar | ? = ayuda" "muted";Write-Host "";$op=Read-Host "DATA_INTAKE";switch($op){"1"{EnsureDemoProfile};"2"{EditManualProfile};"3"{ImportTxtMd};"4"{ImportJson};"5"{OpenPath (IntakeInbox) "INBOX DE ENTRADAS"};"6"{OpenPath (IntakeNormalized) "FICHAS NORMALIZED"};"7"{ShowStatus};"8"{OpenPath (IntakeContracts) "CONTRATOS DATA INTAKE"};"b"{return};""{continue};"?"{ShowHelp};default{UXWarn "Opcion no reconocida";Start-Sleep -Milliseconds 700}}}}
Menu
