$ErrorActionPreference='Stop'
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
$Core='C:\ENGREMIAT_CORE'
$Base=Join-Path $Core 'documents\intake'
$Reports=Join-Path $Core 'reports\launcher'
function W([string]$m,[string]$c='Gray'){try{Write-Host $m -ForegroundColor $c}catch{Write-Host $m}}
function P(){Write-Host '';Read-Host '[Enter] volver / refrescar'|Out-Null}
function Dirs(){foreach($d in @($Base,(Join-Path $Base 'inbox'),(Join-Path $Base 'inbox\pdf'),(Join-Path $Base 'profiles'),(Join-Path $Base 'normalized'),(Join-Path $Base 'reports'),(Join-Path $Base 'archive'),(Join-Path $Base 'samples'),(Join-Path $Base 'contracts'),(Join-Path $Base 'connections'),(Join-Path $Core 'documents\grants'),$Reports)){New-Item -ItemType Directory -Force -Path $d|Out-Null}}
function J($o,[string]$p){$o|ConvertTo-Json -Depth 80|Set-Content $p -Encoding UTF8;$null=Get-Content $p -Raw|ConvertFrom-Json}
function Clean([object]$x){$s=if($null -eq $x){''}else{[string]$x};$s=($s -replace '\s+',' ').Trim();if(!$s){return 'No definido'};return $s}
function MatchFirst([string]$text,[string[]]$patterns){foreach($pat in $patterns){$m=[regex]::Match($text,$pat,[System.Text.RegularExpressions.RegexOptions]::IgnoreCase);if($m.Success -and $m.Groups.Count -gt 1){return Clean $m.Groups[1].Value}};return 'No definido'}
function ListFrom([string]$v){$v=Clean $v;if($v -eq 'No definido'){return @()};return @( ($v -split ',|;|\.' )|ForEach-Object{Clean $_}|Where-Object{$_ -and $_ -ne 'No definido' -and $_.Length -gt 2})}
function LatestStamp(){return Get-Date -Format 'yyyyMMdd-HHmmss'}
function Header([string]$sub=''){Clear-Host;W '==== DATA INTAKE / ENTRADA DE DATOS Y FICHAS ====' Cyan;W 'Ruta: INICIO > [15] Memoria y documentacion > [17] Data Intake / Entrada de datos y fichas' DarkGray;W 'Rol: productor y normalizador local de fichas estructuradas' Gray;if($sub){W $sub Yellow};W ''}
function DemoProfile(){Dirs;$stamp=LatestStamp;$sample=Join-Path $Base 'samples\grant-call-demo-source.json';$norm=Join-Path $Base 'normalized\grant-call-profile-from-intake-latest.json';$active=Join-Path $Core 'documents\grants\grant-call-profile-latest.json';$src=[ordered]@{source_id='intake-demo-grant-call-001';source_type='demo';source_path=$sample;created_at=(Get-Date).ToString('s');status='normalized';human_review_required=$false;title='Convocatoria demo completa'};$p=[ordered]@{profile_id='grant-call-profile-from-intake-latest';profile_type='grant_call';schema='ENGREMIAT_NORMALIZED_PROFILE_CONTRACT_V1';created_at=(Get-Date).ToString('s');status='ready';human_review_required=$false;confidence='high';source=$src;titulo='Convocatoria demo de innovacion social y economia circular';convocatoria_nombre='Convocatoria demo de innovacion social y economia circular';entidad_convocante='Entidad publica demo';entity='Entidad publica demo';territorio='Catalunya / España';territory='Catalunya / España';fecha_limite='2026-12-31';deadline='2026-12-31';importe_maximo='50000 EUR';amount='50000 EUR';modalidad='Subvencion competitiva';objetivo_convocatoria='Financiar proyectos piloto con impacto social, economia circular, digitalizacion local y participacion comunitaria.';encaje_engremiat='Engremiat encaja como infraestructura local-first para coordinar recursos, tareas, documentacion, evidencias y colaboracion humano-maquina.';beneficiarios='Comunidades locales, entidades sociales, pequenos productores, profesionales y administraciones colaboradoras.';criterios=@('Innovacion social','Impacto medible','Viabilidad tecnica','Sostenibilidad','Escalabilidad');criteria=@('Innovacion social','Impacto medible','Viabilidad tecnica','Sostenibilidad','Escalabilidad');documentacion_requerida=@('Memoria tecnica','Presupuesto','Cronograma','Indicadores','Declaracion responsable');required_documents=@('Memoria tecnica','Presupuesto','Cronograma','Indicadores','Declaracion responsable');resumen='Ficha demo completa generada desde Data Intake.';summary='Ficha demo completa generada desde Data Intake.';pending_fields=@();metadata=[ordered]@{producer='ENGREMIAT-DATA-INTAKE-CENTER';local_first=$true;network_used=$false;external_ai_used=$false}};J $src $sample;J $p $norm;Copy-Item $norm $active -Force;Header 'DEMO ACTIVADA';W 'OK ficha_demo_activada=True' Green;W $active Cyan;P}
function ManualProfile(){Dirs;$p=Join-Path $Base 'normalized\grant-call-profile-manual-editable-latest.json';if(!(Test-Path $p)){$o=[ordered]@{profile_id='grant-call-profile-manual-editable-latest';profile_type='grant_call';schema='ENGREMIAT_NORMALIZED_PROFILE_CONTRACT_V1';created_at=(Get-Date).ToString('s');status='pending_review';human_review_required=$true;confidence='none';source=[ordered]@{source_id='manual-form';source_type='manual_form';source_path=$p;status='draft'};titulo='EDITAR TITULO';entidad_convocante='No definido';territorio='No definido';fecha_limite='No definido';importe_maximo='No definido';objetivo_convocatoria='No definido';beneficiarios='No definido';criterios=@();documentacion_requerida=@();resumen='Ficha manual editable.';pending_fields=@('entidad_convocante','territorio','fecha_limite','importe_maximo')};J $o $p};Start-Process notepad.exe $p;Header 'FICHA MANUAL EDITABLE';W 'OK ficha_manual_abierta=True' Green;W $p Cyan;P}
function NormalizeTextSource([string]$sourceFile,[string]$raw,[string]$mode){$stamp=LatestStamp;$entity=MatchFirst $raw @('Entidad convocante\s*:\s*(.+)','Convocante\s*:\s*(.+)','Organismo\s*:\s*(.+)');$territory=MatchFirst $raw @('Territorio\s*:\s*(.+)','Ambito territorial\s*:\s*(.+)','Ámbito territorial\s*:\s*(.+)');$deadline=MatchFirst $raw @('Fecha limite(?: de presentacion)?\s*:\s*([0-9]{1,2}[/.-][0-9]{1,2}[/.-][0-9]{2,4})','Plazo(?: de presentacion)?\s*:\s*([0-9]{1,2}[/.-][0-9]{1,2}[/.-][0-9]{2,4})');$amount=MatchFirst $raw @('Importe maximo(?: por proyecto)?\s*:\s*([^
]+)','Cuantia maxima\s*:\s*([^
]+)');$objective=MatchFirst $raw @('Objeto de la convocatoria\s*:\s*([^
]+)','Objetivo(?: de la convocatoria)?\s*:\s*([^
]+)');$beneficiaries=MatchFirst $raw @('Beneficiarios\s*:\s*([^
]+)','Destinatarios\s*:\s*([^
]+)');$criteria=ListFrom (MatchFirst $raw @('Criterios(?: de valoracion)?\s*:\s*([^
]+)'));$docs=ListFrom (MatchFirst $raw @('Documentacion requerida\s*:\s*([^
]+)','Documentación requerida\s*:\s*([^
]+)'));$summary=MatchFirst $raw @('Resumen\s*:\s*([^
]+)');$pending=@();foreach($kv in @(@('entidad_convocante',$entity),@('territorio',$territory),@('fecha_limite',$deadline),@('importe_maximo',$amount),@('objetivo_convocatoria',$objective),@('beneficiarios',$beneficiaries))){if($kv[1] -eq 'No definido'){$pending+=$kv[0]}};if($criteria.Count -eq 0){$pending+='criterios'};if($docs.Count -eq 0){$pending+='documentacion_requerida'};$found=@($entity,$territory,$deadline,$amount,$objective,$beneficiaries,$summary)|Where-Object{$_ -ne 'No definido'};$confidence=if($found.Count -ge 6 -and $criteria.Count -gt 0 -and $docs.Count -gt 0){'medium'}elseif($found.Count -ge 3){'low'}else{'none'};$src=[ordered]@{source_id='intake-'+$mode+'-'+$stamp;source_type=$mode;source_path=$sourceFile;created_at=(Get-Date).ToString('s');status='normalized';human_review_required=($pending.Count -gt 0);title=[IO.Path]::GetFileNameWithoutExtension($sourceFile);raw_text_length=$raw.Length};$profile=[ordered]@{profile_id='grant-call-profile-from-'+$mode+'-latest';profile_type='grant_call';schema='ENGREMIAT_NORMALIZED_PROFILE_CONTRACT_V1';created_at=(Get-Date).ToString('s');status=if($pending.Count -eq 0){'ready'}else{'pending_review'};human_review_required=($pending.Count -gt 0);confidence=$confidence;source=$src;titulo=[IO.Path]::GetFileNameWithoutExtension($sourceFile);convocatoria_nombre=[IO.Path]::GetFileNameWithoutExtension($sourceFile);entidad_convocante=$entity;entity=$entity;territorio=$territory;territory=$territory;fecha_limite=$deadline;deadline=$deadline;importe_maximo=$amount;amount=$amount;objetivo_convocatoria=$objective;beneficiarios=$beneficiaries;criterios=$criteria;criteria=$criteria;documentacion_requerida=$docs;required_documents=$docs;resumen=$summary;summary=$summary;encaje_engremiat='Ficha generada por Data Intake local.';pending_fields=$pending;metadata=[ordered]@{producer='ENGREMIAT-DATA-INTAKE-CENTER';local_first=$true;network_used=$false;external_ai_used=$false}};$sourcePath=Join-Path $Base ('profiles\intake-source-'+$mode+'-latest.json');$profilePath=Join-Path $Base ('normalized\grant-call-profile-from-'+$mode+'-latest.json');$active=Join-Path $Core 'documents\grants\grant-call-profile-latest.json';J $src $sourcePath;J $profile $profilePath;Copy-Item $profilePath $active -Force;Header 'TXT/MD IMPORTADO Y NORMALIZADO';W ('OK fuente_registrada=True modo='+$mode+' confidence='+$confidence+' pendientes='+$pending.Count) Green;W $profilePath Cyan}
function ImportTxtMd(){Dirs;$inbox=Join-Path $Base 'inbox';$files=@();$files+=Get-ChildItem $inbox -File -Filter '*.txt' -ErrorAction SilentlyContinue;$files+=Get-ChildItem $inbox -File -Filter '*.md' -ErrorAction SilentlyContinue;$files=@($files|Sort-Object LastWriteTime -Descending);if(!$files -or $files.Count -eq 0){$t=Join-Path $inbox 'pegar-convocatoria-aqui.txt';@('PEGA AQUI EL TEXTO DE LA CONVOCATORIA','','Guarda y vuelve a ejecutar [3].')|Set-Content $t -Encoding UTF8;Start-Process notepad.exe $t;Header 'TXT/MD PENDIENTE';W 'PENDING plantilla_txt_creada=True' Yellow;P;return};$f=$files|Select-Object -First 1;$raw=Get-Content $f.FullName -Raw;if($raw -match 'PEGA AQUI EL TEXTO' -or $raw.Trim().Length -lt 80){Start-Process notepad.exe $f.FullName;Header 'TXT/MD INSUFICIENTE';W 'PENDING pega_texto_y_guarda=True' Yellow;P;return};NormalizeTextSource $f.FullName $raw 'txt_md';P}
function ImportJson(){Dirs;$inbox=Join-Path $Base 'inbox';$files=@(Get-ChildItem $inbox -File -Filter '*.json' -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending);if(!$files){Header 'JSON PENDIENTE';W 'PENDING no_hay_json_en_inbox=True' Yellow;P;return};$f=$files|Select-Object -First 1;$j=Get-Content $f.FullName -Raw|ConvertFrom-Json;$dest=Join-Path $Base 'normalized\grant-call-profile-from-json-latest.json';J $j $dest;Copy-Item $dest (Join-Path $Core 'documents\grants\grant-call-profile-latest.json') -Force;Header 'JSON IMPORTADO';W 'OK json_activado=True' Green;W $dest Cyan;P}
function OpenInbox(){Dirs;Start-Process (Join-Path $Base 'inbox')}
function OpenNormalized(){Dirs;Start-Process (Join-Path $Base 'normalized')}
function Status(){Dirs;$sources=@(Get-ChildItem (Join-Path $Base 'profiles') -File -Filter '*.json' -ErrorAction SilentlyContinue);$profiles=@(Get-ChildItem (Join-Path $Base 'normalized') -File -Filter '*.json' -ErrorAction SilentlyContinue);$active=Join-Path $Core 'documents\grants\grant-call-profile-latest.json';Header 'ESTADO';W ('Fuentes registradas: '+$sources.Count);W ('Perfiles normalizados: '+$profiles.Count);W ('Ficha activa documental: '+(Test-Path $active));W '';W 'Ultimos perfiles:' Yellow;$profiles|Sort-Object LastWriteTime -Descending|Select-Object -First 8|ForEach-Object{W ('- '+$_.Name+'  '+$_.LastWriteTime)};P}
function OpenContracts(){Dirs;Start-Process (Join-Path $Base 'contracts')}
function Menu(){Dirs;while($true){Header;W '[1] activar ficha demo completa';W '[2] crear/abrir ficha manual editable';W '[3] importar TXT/MD desde inbox y normalizar';W '[4] importar JSON desde inbox como ficha activa';W '[5] abrir carpeta inbox de entradas';W '[6] abrir carpeta normalized de fichas';W '[7] ver estado de Data Intake';W '[8] abrir contratos Data Intake';W '[b] volver al Centro Documental';W '';W '[Enter] refrescar | b = volver | ? = ayuda' DarkGray;W '';$op=Read-Host 'DATA_INTAKE';switch($op){'1'{DemoProfile};'2'{ManualProfile};'3'{ImportTxtMd};'4'{ImportJson};'5'{OpenInbox};'6'{OpenNormalized};'7'{Status};'8'{OpenContracts};'b'{return};'?'{Header 'AYUDA';W 'Data Intake produce fichas. Centro Documental las consume. No se usa red, IA externa ni scraping.';P};''{continue};default{W 'Opcion no reconocida' Yellow;Start-Sleep -Milliseconds 700}}}}
Menu
