$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$CardRoot = Join-Path $Root "documents\human-cards"
$Inbox = Join-Path $CardRoot "_inbox"
$Index = Join-Path $CardRoot "_index"
function Invoke-HumanCardAssistant(){ $assistant = Join-Path $Root "tools\human-card-assistant.ps1"; if(Test-Path $assistant){ & powershell -NoProfile -ExecutionPolicy Bypass -File $assistant } else { W "PENDIENTE asistente tarjetas humanas" Yellow; Read-Host "Enter = volver" | Out-Null } }
function W([string]$Text,[string]$Color="Gray"){ Write-Host $Text -ForegroundColor $Color }
function Ensure-Dirs(){ foreach($d in @($CardRoot,$Inbox,$Index,(Join-Path $CardRoot "data-intake"))){ New-Item -ItemType Directory -Force -Path $d | Out-Null } }
function New-DataIntakeCard(){ Ensure-Dirs; $now=Get-Date; $day=$now.ToString("yyyy\\MM\\dd"); $dir=Join-Path $Inbox $day; New-Item -ItemType Directory -Force -Path $dir | Out-Null; W ""; $title=Read-Host "Titulo / fuente de entrada"; if([string]::IsNullOrWhiteSpace($title)){ $title="Entrada humana" }; $summary=Read-Host "Dato, necesidad, observacion o idea"; if([string]::IsNullOrWhiteSpace($summary)){ $summary="Pendiente de completar" }; $id="DI-"+$now.ToString("yyyyMMdd-HHmmss")+"-"+(Get-Random -Minimum 1000 -Maximum 9999); $file=Join-Path $dir ($id+"-DATA_INTAKE.md"); $created=$now.ToString("s"); $body=@("# Data Intake","","id: "+$id,"kind: DATA_INTAKE","status: PENDING_CLASSIFICATION","priority: MEDIUM","created_at: "+$created,"source: tools/data-intake.ps1","observer_access: documents/human-cards/_index/observer-inbox.jsonl","","## Titulo / fuente",$title,"","## Entrada",$summary,"","## Clasificacion pendiente","- [ ] necesidad","- [ ] recurso","- [ ] bloqueo","- [ ] idea","- [ ] evidencia","","## Decision","PENDING"); Set-Content -Path $file -Value $body -Encoding UTF8; $entry=[ordered]@{id=$id;kind="DATA_INTAKE";status="PENDING_CLASSIFICATION";priority="MEDIUM";created_at=$created;title=$title;summary=$summary;path=$file;observer_visible=$true}; $json=($entry|ConvertTo-Json -Compress); Add-Content -Path (Join-Path $Index "observer-inbox.jsonl") -Value $json -Encoding UTF8; Set-Content -Path (Join-Path $Index "latest-data-intake.json") -Value $json -Encoding UTF8; W ""; W ("OK data_intake_card_created="+$file) Green; W ("OK observer_index="+(Join-Path $Index "observer-inbox.jsonl")) Green; W "NEXT observer clasifica esta entrada." Cyan; Read-Host "Enter = volver" | Out-Null }
function Show-Index(){ Ensure-Dirs; $idx=Join-Path $Index "observer-inbox.jsonl"; W ""; W "INDICE OBSERVABLE" Cyan; if(Test-Path $idx){ Get-Content $idx -Tail 20 | ForEach-Object { W $_ White } } else { W "Sin indice todavia." Yellow }; Read-Host "Enter = volver" | Out-Null }
while($true){ Clear-Host; W "==== ENGREMIAT / DATA INTAKE ====" Cyan; W ""; W ("Almacen: "+$CardRoot) DarkGray; W "Contrato: entrada humana -> tarjeta DATA_INTAKE -> indice observable -> observer" DarkGray; W ""; W "[1] Crear entrada Data Intake" White; W "[2] Ver indice observable" White; W ""; W "[b/q] salir/volver | m = mantenimiento | ? = ayuda | Enter = refrescar" DarkGray; W ""; $cmd=Read-Host "DATA"; $cmd=($cmd+"").Trim().ToLowerInvariant(); switch($cmd){ "" { continue } "1" { New-DataIntakeCard } "2" { Show-Index } "m" { Invoke-HumanCardAssistant } "?" { W "AYUDA" Cyan; W "Data Intake convierte datos, ideas, necesidades o evidencias humanas en tarjetas observables para el observer." White; W "Indice: documents/human-cards/_index/observer-inbox.jsonl" White; Read-Host "Enter = volver" | Out-Null } "b" { break } "q" { break } default { W "Comando no reconocido" Yellow; Read-Host "Enter = volver" | Out-Null } } }


