param([string]$Command="build-fixture",[string]$TaskId="AW-TASK-LOCAL-001")
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function EnsureDir($p){ if($p -and !(Test-Path -LiteralPath $p)){ New-Item -ItemType Directory -Path $p -Force | Out-Null } }
function WriteJson($p,$o){ EnsureDir (Split-Path -Parent $p); $o | ConvertTo-Json -Depth 100 | Set-Content -LiteralPath $p -Encoding UTF8 }
function LoadJson($p){ if(!(Test-Path -LiteralPath $p)){ return $null }; return (Get-Content -LiteralPath $p -Raw -Encoding UTF8 | ConvertFrom-Json) }
function HasProp($obj,$name){ if($null -eq $obj){ return $false }; return @($obj.PSObject.Properties.Name) -contains $name }
function BuildPackage($taskId){ $policy=LoadJson "data/dev-assisted-worker/assisted-worker-policy.json"; $ctx=LoadJson "data/dev/context-snapshot.json"; $active=LoadJson "data/dev/active-row.json"; $stepId=$(if($active -and (HasProp $active "step_id")){$active.step_id}else{"UNKNOWN_STEP"}); $pkg=[ordered]@{ task_id=$taskId; objective_id=$(if($ctx -and (HasProp $ctx "objective_id")){$ctx.objective_id}else{"ENGREMIAT_DEV_ASSISTED_WORKER_ADAPTER_001"}); stage_id=$(if($ctx -and (HasProp $ctx "active_stage")){$ctx.active_stage}else{"E01"}); block_id=$(if($ctx -and (HasProp $ctx "active_block")){$ctx.active_block}else{"B01.2"}); step_id=$stepId; worker_target="CLINE_OR_OLLAMA"; mode="PROPOSAL_ONLY"; context=[ordered]@{ active_context=$ctx; active_row=$active; instruction="Generar propuesta, no aplicar cambios." }; allowed_paths=$policy.allowed_paths; forbidden_paths=$policy.forbidden_paths; allowed_actions=$policy.allowed_actions; forbidden_actions=$policy.forbidden_actions; expected_output=@("agent-result-proposal.json","summary.md","evidence-manifest.json"); gate_policy=[ordered]@{ human_gate_before_apply=$true; proposal_only=$true; apply_allowed=$false }; created_at=(Get-Date).ToString("s") }; return $pkg }
function ValidatePackage($pkg){ $bad=@(); foreach($k in @("task_id","objective_id","stage_id","block_id","step_id","worker_target","mode","context","allowed_paths","forbidden_paths","allowed_actions","forbidden_actions","expected_output","gate_policy","created_at")){ if(-not (HasProp $pkg $k)){ $bad += "missing:"+$k } }; foreach($fa in @($pkg.forbidden_actions)){ if(@($pkg.allowed_actions) -contains $fa){ $bad += "forbidden_action_allowed:"+$fa } }; if($pkg.mode -eq "LOCAL_AUTHORIZED" -and -not $pkg.gate_policy.human_gate_before_apply){ $bad += "local_authorized_without_gate" }; return $bad }
switch($Command){
  "build-fixture" { $pkg=BuildPackage $TaskId; WriteJson "data/dev-assisted-worker/tasks/$TaskId/agent-task-package.json" $pkg; Write-Host ("OK assisted_task_package=data/dev-assisted-worker/tasks/"+$TaskId+"/agent-task-package.json mode="+$pkg.mode+" step="+$pkg.step_id); break }
  "validate-fixture" { $pkg=LoadJson "data/dev-assisted-worker/agent-task-package.fixture.json"; $bad=ValidatePackage $pkg; if($bad.Count -gt 0){ Write-Host ("ERR assisted_task_fixture errors="+($bad -join ",")); exit 1 }; Write-Host "OK assisted_task_fixture_valid=True"; break }
  "validate" { $pkg=LoadJson "data/dev-assisted-worker/tasks/$TaskId/agent-task-package.json"; if($null -eq $pkg){ throw "Falta paquete: $TaskId" }; $bad=ValidatePackage $pkg; if($bad.Count -gt 0){ Write-Host ("ERR assisted_task_package errors="+($bad -join ",")); exit 1 }; Write-Host ("OK assisted_task_package_valid=True task_id="+$TaskId); break }
  default { Write-Host "Uso: .\tools\eng-assisted-task-builder.ps1 build-fixture [TaskId]|validate-fixture|validate [TaskId]" }
}
