param([string]$Command="prompt-status",[switch]$NoOpen)
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function RunScript([string]$p,[string[]]$a=@()){if(!(Test-Path -LiteralPath $p -PathType Leaf)){throw "Falta script: $p"};& powershell -NoProfile -ExecutionPolicy Bypass -File $p @a;if($LASTEXITCODE -ne 0){throw "Fallo comando: $p"}}
function ReadJson([string]$p){if(Test-Path -LiteralPath $p -PathType Leaf){try{return Get-Content -LiteralPath $p -Raw -Encoding UTF8|ConvertFrom-Json}catch{return $null}};return $null}
if($Command -eq "prompt-status"){$m=ReadJson "prompts/outbox/manifest.json";$n=ReadJson "data/prompt-factory/out/next-step.json";$a="NONE";$c=0;if($m){$a=[string]$m.active_prompt_id;$c=[int]$m.published_count};$step="UNKNOWN";if($n){$step=[string]$n.selected.step_id};Write-Host ("OK prompt_status=True active_prompt="+$a+" published_count="+$c+" next_step="+$step+" outbox=prompts/outbox inbox=prompts/inbox");exit 0}
if($Command -eq "prompt-next"){RunScript "tools/prompt-factory/Build-PromptContext.ps1" @("-NextPath","data/prompt-factory/out/next-step.json","-OutPath","data/prompt-factory/out/prompt-context.json");RunScript "tools/prompt-factory/Build-PromptNext.ps1" @("-ContextPath","data/prompt-factory/out/prompt-context.json","-OutPath","data/prompt-factory/out/PROMPT_NEXT.md");RunScript "tools/prompt-factory/Publish-Prompt.ps1" @("-PromptPath","data/prompt-factory/out/PROMPT_NEXT.md","-Type","NEXT","-OutboxRoot","prompts/outbox");Write-Host "OK prompt_next=True active=prompts/outbox/ACTIVE_PROMPT.md";exit 0}
if($Command -eq "prompt-repair"){RunScript "tools/prompt-factory/Find-LastDevelopmentIssue.ps1" @("-OutPath","data/prompt-factory/out/last-issue.json");RunScript "tools/prompt-factory/Build-PromptRepair.ps1" @("-IssuePath","data/prompt-factory/out/last-issue.json","-OutPath","data/prompt-factory/out/PROMPT_REPAIR.md");RunScript "tools/prompt-factory/Publish-Prompt.ps1" @("-PromptPath","data/prompt-factory/out/PROMPT_REPAIR.md","-Type","REPAIR","-OutboxRoot","prompts/outbox");Write-Host "OK prompt_repair=True active=prompts/outbox/ACTIVE_PROMPT.md";exit 0}
if($Command -eq "prompt-open"){if(!(Test-Path -LiteralPath "prompts/outbox/ACTIVE_PROMPT.md" -PathType Leaf)){throw "No existe prompts/outbox/ACTIVE_PROMPT.md"};if(-not $NoOpen){Start-Process (Resolve-Path "prompts/outbox/ACTIVE_PROMPT.md")};Write-Host "OK prompt_open=True active=prompts/outbox/ACTIVE_PROMPT.md";exit 0}
if($Command -eq "prompt-inbox"){RunScript "tools/prompt-factory/Import-WorkerResponse.ps1" @("-InboxRoot","prompts/inbox","-ReportPath","reports/prompt-factory/e06-integracion-eng-ps1/worker-response-import-report.json");Write-Host "OK prompt_inbox=True report=reports/prompt-factory/e06-integracion-eng-ps1/worker-response-import-report.json";exit 0}
Write-Host "Uso: .\eng.ps1 prompt-status | prompt-next | prompt-repair | prompt-open | prompt-inbox";exit 0
