param([string]$InputPath="data/prompt-factory/input/development-plan.sample.tsv",[string]$PlanPath="data/prompt-factory/out/plan-normalized.json",[string]$NextPath="data/prompt-factory/out/next-step.json",[string]$ReportPath="reports/prompt-factory/e02-lector-plan-desarrollo/development-plan-reader-smoke-report.json")
$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function EnsureDir([string]$p){if($p -and !(Test-Path -LiteralPath $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null}}
function WriteJson([string]$p,$o){EnsureDir(Split-Path -Parent $p);$o|ConvertTo-Json -Depth 100|Set-Content -LiteralPath $p -Encoding UTF8}
$checks=@();$score=0;function AddReaderCheck([string]$id,[bool]$ok,[int]$points,[string]$message){if($ok){$script:score+=$points};$script:checks+=[ordered]@{id=$id;ok=$ok;points=$points;message=$message}}
$inputOk=Test-Path -LiteralPath $InputPath -PathType Leaf;$planOk=Test-Path -LiteralPath $PlanPath -PathType Leaf;$nextOk=Test-Path -LiteralPath $NextPath -PathType Leaf;AddReaderCheck "input_exists" $inputOk 10 $InputPath;AddReaderCheck "plan_exists" $planOk 15 $PlanPath;AddReaderCheck "next_exists" $nextOk 15 $NextPath
$rows=0;$stages=0;$blocks=0;$selectedOk=$false;if($planOk){$plan=Get-Content -LiteralPath $PlanPath -Raw -Encoding UTF8|ConvertFrom-Json;$rows=[int]$plan.rows_count;$stages=@($plan.stages).Count;$blocks=0;foreach($st in @($plan.stages)){$blocks+=@($st.blocks).Count}};if($nextOk){$nx=Get-Content -LiteralPath $NextPath -Raw -Encoding UTF8|ConvertFrom-Json;$selectedOk=($nx.selected.step_id -and $nx.selected.artifact -and $nx.selected.dependency)}
AddReaderCheck "rows_ge_6" ($rows -ge 6) 20 ("rows="+$rows);AddReaderCheck "stages_ge_1" ($stages -ge 1) 10 ("stages="+$stages);AddReaderCheck "next_selected" $selectedOk 20 $NextPath;AddReaderCheck "required_tools_exist" ((Test-Path -LiteralPath "tools/prompt-factory/Import-DevelopmentPlan.ps1") -and (Test-Path -LiteralPath "tools/prompt-factory/Select-NextPlanStep.ps1")) 10 "tools"
if($score -gt 100){$score=100};$ok=($score -ge 90);$rep=[ordered]@{objective_id="ENGREMIAT_CORE_MVP_PROMPT_FACTORY_001";stage_id="E02";repair="E02-IMPORT-TSV-PADDING-REPAIR-001";block_id="B02.3";step_id="P02.3.2";status=$(if($ok){"OK"}else{"NO_GO"});validation_passed=$ok;score=$score;threshold=90;rows=$rows;stages=$stages;blocks=$blocks;checks=$checks;input=$InputPath;plan=$PlanPath;next_step=$NextPath;external_network=$false;git=$false;next=$(if($ok){"E03_GENERADOR_PROMPT_NEXT"}else{"REPAIR_PROMPT_FACTORY_E02"});checked_at=(Get-Date).ToString("s")}
WriteJson $ReportPath $rep
if(-not $ok){Write-Host ("ERR development_plan_reader=False score="+$score+" report="+$ReportPath);exit 1}
Write-Host ("OK development_plan_reader=True repair=E02-IMPORT-TSV-PADDING-REPAIR-001 score="+$score+" rows="+$rows+" report="+$ReportPath+" next=E03_GENERADOR_PROMPT_NEXT")
