$ErrorActionPreference="Stop"
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new()
function EnsureDir([string]$Path){if($Path -and !(Test-Path -LiteralPath $Path)){New-Item -ItemType Directory -Path $Path -Force|Out-Null}}
function ReadJsonFile([string]$Path){if(!(Test-Path -LiteralPath $Path -PathType Leaf)){throw ("Falta JSON: "+$Path)};return Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}
function WriteJsonFile([string]$Path,$Object){EnsureDir (Split-Path -Parent $Path);$Object|ConvertTo-Json -Depth 100|Set-Content -LiteralPath $Path -Encoding UTF8}
try{
$PlanPath=[string]$args[0];$OutPath=[string]$args[1];if([string]::IsNullOrWhiteSpace($PlanPath)){$PlanPath="data/plan-to-worker/plan-normalized.json"};if([string]::IsNullOrWhiteSpace($OutPath)){$OutPath="data/plan-to-worker/selected-step.json"}
$plan=ReadJsonFile $PlanPath
$allSteps=@();foreach($stageItem in @($plan.stages)){foreach($blockItem in @($stageItem.blocks)){foreach($stepItem in @($blockItem.steps)){$allSteps+=[ordered]@{stage_id=[string]$stageItem.stage_id;stage_name=[string]$stageItem.name;block_id=[string]$blockItem.block_id;block_name=[string]$blockItem.name;step_id=[string]$stepItem.step_id;title=[string]$stepItem.title;artifact=[string]$stepItem.artifact;depends_on=[string]$stepItem.depends_on;format=[string]$stepItem.format;risk=[string]$stepItem.risk;requires_human=[string]$stepItem.requires_human;priority=[string]$stepItem.priority;status=[string]$stepItem.status;notes=[string]$stepItem.notes}}}}
$doneIds=@();foreach($s in $allSteps){if(([string]$s.status) -eq "DONE"){$doneIds+=[string]$s.step_id}}
$selected=$null;$reason="NO_PENDING_READY_STEP";$dependencyState="NONE"
foreach($s in $allSteps){$st=[string]$s.status;if($st -ne "PENDING"){continue};$dep=[string]$s.depends_on;if([string]::IsNullOrWhiteSpace($dep) -or $dep -eq "NONE"){$selected=$s;$reason="FIRST_PENDING_WITHOUT_DEPENDENCY";$dependencyState="READY_NO_DEPENDENCY";break};if($doneIds -contains $dep){$selected=$s;$reason="FIRST_PENDING_DEPENDENCY_DONE";$dependencyState="READY_DEPENDENCY_DONE";break};$known=$false;foreach($x in $allSteps){if([string]$x.step_id -eq $dep){$known=$true}};if(-not $known){$selected=$s;$reason="FIRST_PENDING_EXTERNAL_DEPENDENCY_ASSUMED_READY";$dependencyState="READY_EXTERNAL_DEPENDENCY";break}}
if($null -eq $selected){$out=[ordered]@{objective_id=$plan.objective_id;decision="NO_GO";selected=$false;reason=$reason;next="NO_READY_STEP";external_network=$false;git_write=$false;worker_real_execution=$false;created_at=(Get-Date).ToString("s")}}else{$out=[ordered]@{objective_id=$plan.objective_id;decision="NEXT";selected=$true;reason=$reason;dependency_state=$dependencyState;stage_id=$selected.stage_id;stage_name=$selected.stage_name;block_id=$selected.block_id;block_name=$selected.block_name;step_id=$selected.step_id;title=$selected.title;artifact=$selected.artifact;depends_on=$selected.depends_on;format=$selected.format;risk=$selected.risk;requires_human=$selected.requires_human;priority=$selected.priority;status=$selected.status;notes=$selected.notes;external_network=$false;git_write=$false;worker_real_execution=$false;created_at=(Get-Date).ToString("s")}}
WriteJsonFile $OutPath $out
Write-Host ("OK select_next=True selected="+$out.selected+" decision="+$out.decision+" step="+$out.step_id+" out="+$OutPath)
}catch{Write-Host ("ERR select_next=False message="+$_.Exception.Message) -ForegroundColor Red;throw}
